### ISSUE TITLE
OBS crashing as soon I start streaming

### ISSUE THREAD

**Issue by Xbye** [Xaymar/OBS-AMD-Advanced-Media-Framework#128] opened 2016-11-04 00:34 UTC
Crash log:
http://pastebin.com/CvZtZJXy

New OBS log:
https://gist.github.com/anonymous/24a3acd467d1dde5ff707d033891a06d

Honestly not sure what's causing it.

**Comment by NickParks** [comment] 2016-11-04 00:38
Duplicate of #124 except you provide two separate logs

**Comment by Xbye** [comment] 2016-11-04 00:42
> I posted over at Issue #128 . I believe I found the culprit!
> 
> Try setting "profile level" to something rather than leaving it at "automatic".

**Closed as completed** 2016-11-04 00:42 UTC
Labels: type:duplicate, status:solved
