### ISSUE TITLE
When using AMF to Stream and Record, weird "Crash" happening

### ISSUE THREAD

**Issue by diagoon83** [Xaymar/OBS-AMD-Advanced-Media-Framework#363] opened 2019-02-23 20:51 UTC
So, I'll try and explain this situation the best I can but since it seems fairly complicated feel free to ask me for more details.

I stream on x264 and record using AMF, H265. Thing is: I've been recently having this weird glitch where the stream goes 0kb/s (and my internet is fine, though Twitch shows it like I've stopped streaming. also, considering it has happened 15 minutes in, 20 minutes in, 30 minutes in and 1 hour in, I think it has nothing to do with some sort of stream time limiter) and the recording never actually finishes "Stop Recording".

I have to shut down OBS through the Task Manager (since it won't let me close it when the recording is in limbo). Once I restart it, AMF is missing. I have to restart my computer to have it back on and to have the same thing to happen every 20 or so minutes.

Since OBS doesn't necessarily "crash" it doesn't create a Crash Log, but here are two normal logs showing the two problems happening (first one is when the stream goes down and so does the recording and second one is when AMF is ""missing""):

[2019-02-23 17-14-27.txt](https://github.com/obsproject/obs-amd-encoder/files/2897242/2019-02-23.17-14-27.txt)
[2019-02-23 17-45-18.txt](https://github.com/obsproject/obs-amd-encoder/files/2897243/2019-02-23.17-45-18.txt)

I have streamed on the same AMF version and AMD driver many times before with no problem whatsoever, so I really don't get what is going on. Some days ago, I had the same issue, updated the AMD drivers to the latest version (19.2.2) and was able to record/stream without any problems. Recently, though, even these drivers have been causing this same problem.

My specifications are the following:
OS: Windows 10 64bit (updated)
CPU: i7 7700 3.6GHz
RAM: 16GB DDR4 2400MHz
Motherboard: ASRock B250M-HDV
GPU: Sapphire Radeon RX 480 Nitro +
HDD: Seagate ST2000DL003-9VT166

**Comment by Xaymar** [comment] 2019-02-23 22:53
Please try all the steps outlined in the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). It looks like you might have a faulty Driver installation, so [this guide](https://github.com/obsproject/obs-amd-encoder/wiki/Frequently-Asked-Questions#q-how-do-i-perform-a-full-clean-uninstall-of-the-amd-driver) might be of use if you do not know how to properly use Display Driver Uninstaller.

**Comment by Benman2785** [comment] 2019-02-28 16:47
heard of similar with older versions of OBS - even with x264

**Comment by diagoon83** [comment] 2019-03-04 22:32
Hello. I had a clean Driver reinstall and it helped me, I didn't have the issue happening for the past week. As you can see in this, I was able to stream/record for a long period of time with no issues.
[2019-03-03 17-17-31.txt](https://github.com/obsproject/obs-amd-encoder/files/2928461/2019-03-03.17-17-31.txt)

However, today, with no software update, this happened:
[2019-03-04 17-56-37.txt](https://github.com/obsproject/obs-amd-encoder/files/2928452/2019-03-04.17-56-37.txt)
"Input Queue is full, encoder is overloaded!"

Please note no OBS configuration has changed as well, I'm using the same scene and playing the same game. I really don't know why this happens, but will try and reinstall my drivers to see if it happens again.

**Comment by Xaymar** [comment] 2019-03-06 02:04
See #350 and plenty of previous issue reports with the same/similar bug. The cause for this varies:

- Is your card overclocking, either by factory or by user? Most vendors overclock without checking full functionality, so you should make sure everything works by underclocking back to proper stock clocks.
- Have you tried running a temperature heavy benchmark on the GPU to see if there's any noticable problems? The card may be reaching the end of its lifetime, for probably unknown reasons.
- Also make sure that your cooling is working right. Most AMD cards come with a fan curve that doesn't cool them at all above >70°C, and they can usually go much higher in RPM.

Also make sure to contact AMD Support with this bug through any and all means. This bug has been around since Media SDK days and has still not been fixed. I'm sure there has been more than a single report to AMD about this.

**Comment by Xaymar** [comment] 2019-07-20 21:08
Is this still happening?

**Comment by diagoon83** [comment] 2019-08-17 18:20
> Is this still happening?

Hello, sorry for the slow response. Yes, in fact, it didn't happen for two weeks or so but lately, it's happening again - no AMD driver update installed or anything different.

- I toned down my GPU's clock to it's normal value (1208MHz), and applied new fan speeds to make sure it stays cool.
- I am still not sure what causes this crash, since the only notable thing is the GPU usage on the Task Manager going up to 100% and then dropping to very low values.

**Comment by Xaymar** [comment] 2019-09-29 10:33
Please update your AMD Driver and see if it still happens with the most recent one.

**Comment by Xaymar** [comment] 2019-10-13 03:19
This is probably fixed by the pending 2.6 release

**Comment by Xaymar** [comment] 2020-01-21 09:16
Since there has been no activity, I'm guessing that this has been fixed.

**Closed as completed by Xaymar** 2020-01-21 09:16 UTC
Labels: type:support
