### ISSUE TITLE
Tooltips not lined up/written properly

### ISSUE THREAD

**Issue by Xbye** [Xaymar/OBS-AMD-Advanced-Media-Framework#129] opened 2016-11-04 00:59 UTC
**Image**:
https://cdn.discordapp.com/attachments/236980395386732554/243901412063444994/unknown.png

Seems to be random which tooltips are accurate and which are not. Sometimes displays tooltips for options not even visible.

**Comment by Xaymar** [comment] 2016-11-04 07:32
I'm not sure what the problem is?

**Comment by Xaymar** [comment] 2016-11-04 08:03
Oh i see now, you somehow managed to get a tooltip for a property that is invisible.

**Comment by Xaymar** [comment] 2016-11-04 08:04
Could you report that to the [OBS Project tracker](https://obsproject.com/mantis/) instead?

**Comment by Xaymar** [comment] 2016-11-04 08:08
That's the correct label i wanted to have. Will be fixed soonish

**Closed as completed** 2016-11-04 08:14 UTC
Labels: type:bug, status:solved
