### ISSUE TITLE
RX 4XX cards can't do Quality Preset 'Quality' well

### ISSUE THREAD

**Issue by Shivansps** [Xaymar/OBS-AMD-Advanced-Media-Framework#123] opened 2016-11-03 03:46 UTC
# Maintainer Cleanup
RX 4XX cards have trouble using Quality Preset 'Quality' with H.264. This is a non-issue, as it isn't caused by the plugin but by the user. If you are a a user and reading this, congratulations, you found out why it happens. Use Speed or Balanced Quality Preset instead.

### Specs:
* Core i5-2500k
* 18GB DDR3-1333
* 1TB HDD (Game) + 500GB HDD(Recording)
* MSI RX480 8GB
* OBS Version: OBS 0.16.2 (64bit, W10)
* Plugin Version: [AMF Encoder] Version 1.3.3.1-1.3.0.5
* AMD Driver: [16.10.3 Hotfix](https://www2.ati.com/drivers/beta/non-whql-win10-64bit-radeon-software-crimson-16.10.3-oct27.exe)

### LOG / Video:
* https://mega.nz/#!ytJCXD4Q!k1_xXvBnZcWdQBn6O134UPjZt8GAOltbekRYogcScfU
* https://gist.github.com/anonymous/04596fe6d1edb844640e96dd3f6d5bc6

### Original Message

> OK, im trying now to record using this settings http://i.imgur.com/rcs45sD.png
> All default or recomended, all recording have this kind of shuttering or lag, not sure how to call it, you can see it on the sample video, the game looks perfect, 100% fluid and can keep up with the 60 fps lock, but the recording is just, bad, trying to work around the issue tryied to:
> -Enable OpenCL/DX11 memory
> -Change profile level or leave it automatic
> -Change profile quality to : Balanced and speed
> -Use VBR or VBR_LAT
> -Drop the recording FPS and Game to 30fps.
> 
> Of the that, only using 30 fps instead of 60 helped, it did not fix the issue compeltely, it is still there, but can be noticed less.

**Comment by Xaymar** [comment] 2016-11-03 07:06
Issue is caused by your settings being too taxing for the GPU encoder. Nothing I can do here.

**Comment by Shivansps** [comment] 2016-11-03 20:37
Tested with 16.9.2 after removing 16.10.3 with DDU, same issue.
https://gist.github.com/anonymous/04596fe6d1edb844640e96dd3f6d5bc6

Also did you see the percent of lagged/drooped frames? Thats enoght to cause all the issues as seem in the sample?

Im starting to belive this may be related to VBR issue, you think that under VBR the encoder will keep way lower bitrates than it should if it cant keep up?

**Comment by Xaymar** [comment] 2016-11-03 20:41
Removing 16.10.3 with DDU doesn't actually seem to downgrade for some reason - issues that were 16.10.3 only stick around even after downgrading, no idea why. 16.11.1 might help fix some of these as well as 1.4.0.0.

**Comment by Shivansps** [comment] 2016-11-04 02:04
I only been able to record at 30 fps on the new driver/plugin/obs versions, but i can tell you right now the issue persist.

https://gist.github.com/anonymous/8dfd95600d1967380d1051b4ed4a9b0c

**Comment by Xaymar** [comment] 2016-11-04 18:49
The issue can't be fixed on my end, it is a system/configuration issue as I explained here: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/123#issuecomment-258075553

**Comment by Shivansps** [comment] 2016-11-04 22:45
You can close this, this is most likely OBS side issue, also happens with QSV of my cpu.

**Comment by Keridos** [comment] 2016-11-05 02:20
Also encountering this when trying to record 1920x1200 at 60fps on Quality preset. According to my log file (https://gist.github.com/Keridos/10dbf84aabd348b33e7a6506e358e964) the hardware encoding works (opencl plus dx11). I do however not get this if I downscale the video.

**Comment by Xaymar** [comment] 2016-11-05 05:05
All logs here have the input queue full issue that is usually caused by
configurations. If i could reproduce this, that would make things much
easier.

**Comment by Xaymar** [comment] 2016-11-05 13:14
All of you are using Quality Preset 'Quality', which is the slowest of the three encoding presets. Please use 'Balanced' or 'Speed' instead for RX 4XX cards, since their feature set is somewhat in-between VCE1.0 and VCE2.0 due to the HEVC support.

If you are using Presets, make sure to deselect it before trying that. Presets override most of your settings for values that the preset needs to be a preset - that's what a preset does, it's in the name itself.

**Comment by gortboy** [comment] 2016-11-05 14:08
Do we have any sort of general Idea on the bitrate/framerate/resolution limitations of the various VCE versions?  I know I at 2560x1440@60 and CBR bitrate of 18Mbps on the Fury X I run into the similar issues.  It takes far longer for it to occur when I set quality to speed but it still happens anyways.

[2016-11-05 08-26-20.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/573235/2016-11-05.08-26-20.txt)

**Comment by Xaymar** [comment] 2016-11-05 14:12
There's an entire wiki page dedicated to that: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware,-GCN-and-VCE-Limits

**Comment by gortboy** [comment] 2016-11-05 14:29
I had looked at that :) VCE 3.0 does claim to be able to do 4k at 90fps, but I get the feeling this isn't realistic if I am dropping frames at 1440.   Maybe the bitrate is too high? Even there the card technically claims to support up to 100 Mbps.

**Comment by Xaymar** [comment] 2016-11-05 14:41
Technically a Fury X should be capable of 4K 60 fps with Quality Preset 'Speed', since it is a "slightly" overpowered version of my R9 285 (just slightly, not like 300% better at all). 1440p should be possible at 120 fps with quality preset speed too, however I didn't test 1440p - that data came from the PR guy on reddit.

**Comment by Shivansps** [comment] 2016-11-05 18:57
Maintainer edit: Left this one for clarity for the next commit message.

> Also, and this one is a bug, i had to manually set the profile level to 4.2, because if it left in auto it will use 4.1, and 4.1 is not enoght for 1920x1080@60 fps.

**Comment by Xaymar** [comment] 2016-11-05 19:42
I fixed the Automatic profile level thing now, slight oversight on my part.

**Comment by Shivansps** [comment] 2016-11-05 21:52
here is the sample video, shutter can be noticed(may be OBS related but i no idea why) and some kind of glitch with quality, you will see what i mean if you look closely at it.

https://mega.nz/#!7gZ2xByZ!LLK64-wUvXE-YcyM2mQBkukDauH6jTrZyw7tSZUFM7I

**Comment by Keridos** [comment] 2016-11-05 22:01
@Xaymar Try to encode 1920x1200 (which is slightly higher than full HD) at 60fps on quality preset, I think balanced works fine for me there. But still I remember that AMD Marketing told me that my RX480 should be fast enough for 4K@60fps.

**Comment by Xaymar** [comment] 2016-11-05 22:14
@Shivansps I'll take a look.

@Keridos [4K@60fps with HEVC, not H.264](https://www.reddit.com/r/Amd/comments/4y10gr/today_we_released_a_new_version_of_the_amd_media/d6kkje0/)

**Comment by Keridos** [comment] 2016-11-05 22:16
Ah yeah my bad, but that still tells it supports 1440p@60fps in h264.

**Comment by Xaymar** [comment] 2016-11-05 22:18
Well, does it? If you tested it and it didn't work then it clearly doesn't. :P

**Comment by Keridos** [comment] 2016-11-05 22:18
I tested less resolution than that at quality preset and It did not work :P

**Comment by Xaymar** [comment] 2016-11-05 22:39
@Shivansps What should I look for? I saw the QP value shoot up once, but the rest looked okay to me?

**Comment by Shivansps** [comment] 2016-11-05 22:55
@Xaymar
For example at 0:53-1:05 look just below the middle of the video, it happens about twice on there.

Also, i just tested recording with Windows 10 built-in GameDVR, seems a lot better, it records at 41mbps, quality is good, the video is more fluid and shutter seems to happen, but is way more rare (i belive it happens when the encoder drops a frame, i just cant be sure).

**Comment by Xaymar** [comment] 2016-11-05 23:27
@Shivansps That's QP spiking, it happens when the latency to the GPU increases due to bandwidth load increasing (games pushing data to the GPU for example). GameDVR doesn't use VBR_LAT as far as I am aware, it uses VBR with Speed Quality Preset.

**Comment by Shivansps** [comment] 2016-11-05 23:36
I see... do you think that PCI-E 2.0 x16 may be causing that issue? We could be against the wall of what PCI-E 2.0 can do?

Strange that VBR is working that well on GameDVR, because its almost always on 41mbps and quality is petty much the same on the entire video. mmm strange.

**Comment by Xaymar** [comment] 2016-11-05 23:39
@Shivansps You misunderstand what VBR_LAT is. VBR_LAT is variable bitrate that takes into account how much time has passed for an encoded frame, so that it always returns one for a given framerate (if possible). VBR doesn't do that, VBR just encodes as fast as it can with the given settings, ignoring latency and usage.

**Comment by Shivansps** [comment] 2016-11-05 23:52
@Xaymar 
Thats not what i mean, i was not traying to compare it to VBR_LAT, i tried using VBR before, in OBS and other programs, like Plays.TV(it always use it), and quality really suffers because sometimes the bitrate goes WAY below from what i set as a target and quality suffers as a result of it, thats why i could not really trust it before, i could set 40mbps as a target, may work OK for 2min video, but for an hour long video the overall bitrate can get all the way down to 10mbps... thats why i stopped using Plays.TV, and i had similar experiences with OBS as well. That why im suprised that it seems to work OK on GameDVR.

So the quality and shutter problems ive been having using "speed" presets may be related to PCI-E 2.0 bandwidth, and using "quality" cant be done because the encoder cant keep up.

**Comment by Xaymar** [comment] 2016-11-05 23:53
I'm not sure what GameDVR uses internally (Media Foundation perhaps? If so, it's actually using CBR with Filler Data), but the VBR drop over long time is not related to this issue at all.

-- Cleanup marker --

**Comment by Xaymar** [comment] 2016-11-06 00:02
I did a big cleanup here as most of the information posted in this thread was useless. The solution for the problem was in the 2nd comment, anything else was pretty much a bloat like a toolbar for Internet Explorer.

**Closed as completed** 2016-11-12 15:40 UTC
Labels: status:user error, type:support
