### ISSUE TITLE
OBS gets stuck on "Stopping Stream/Recording" and continues writing file until I kill it from task manager

### ISSUE THREAD

**Issue by acleee** [Xaymar/OBS-AMD-Advanced-Media-Framework#350] opened 2018-12-10 22:38 UTC
Log file: https://obsproject.com/logs/vDKSEWVrFENE2BnF

Basically what occurs is this:

- I start a recording/stream
- I go to stop the recording/stream
- OBS hangs on "stopping xyz..." and the buttons become nonresponsive (my log is from when it stuck on stopping recording)
- I close OBS by hitting the X in the corner
- OBS continues running in the background and continues streaming/recording to the FLV file until i kill it from task manager

Specs: 

`Operating System`
`	Windows 7 Ultimate 64-bit SP1`
`CPU`
`	Intel Core i7 4790K @ 4.00GHz `
`RAM`
`	16.0GB Dual-Channel DDR3 @ 666MHz (9-9-9-24)`
`Motherboard`
`	ASUSTeK COMPUTER INC. Z97-E (SOCKET 1150)`
`Graphics`
`	4096MB ATI AMD Radeon R9 380`
`Storage`
`	1863GB Seagate ST2000DM006-2DM164 ATA Device (SATA )`
`	167GB INTEL SSDSC2CW180A ATA Device (SATA (SSD))`

**Comment by Xaymar** [comment] 2018-12-22 19:39
Your GPU encoder seems to have frozen, never returning the first frame. OBS does not stop a stream before a keyframe appears. Since the encoder plugin does not provide any time out for this behavior, and it is not considered an error either right now, nothing will happen and it will look like OBS is stuck stopping recording.

**Comment by gety9** [comment] 2019-02-28 01:18
@acleee @Xaymar 

any solution to this? i started having exactly same issue

**Comment by Xaymar** [comment] 2019-02-28 12:27
@gety9 Well, from what I know of the bug (even through reproducing the behavior myself), the AMD Driver simply stops doing encoder things for an unknown reason. It might cause the plugin to get stuck in SubmitInput or QueryOutput, or might just always return AMF_OK but have no data. All of it points to faulty overclocks, faulty cooling or faulty drivers.

**Comment by Xaymar** [comment] 2019-07-20 21:07
Closing as unfixable.

**Closed as completed by Xaymar** 2019-07-20 21:07 UTC
Labels: status:wontfix, type:support
