### ISSUE TITLE
Weak System causes Variable Framerate Output

### ISSUE THREAD

**Issue by alincupunct** [Xaymar/OBS-AMD-Advanced-Media-Framework#146] opened 2016-11-16 15:51 UTC
Speccy : http://i.imgur.com/KMHI9xp.png
OBS Version : 0.16.5
Plugin Version : [AMF Encoder] Version 1.4.1.5-1.3.0.5
AMD Driver : 16.11.3 (it did this on 16.11.2 too)
VOD : https://www.twitch.tv/acpbot/v/101424284 
Log : https://gist.github.com/2b001daae405cf43fabe021f2be4c5ae
Description of the issue : In the vod at around 19 seconds in , 50 seconds in and it keeps freezing through the time I take to select my champion. Sometimes it does this in-game  (not this time though , https://www.twitch.tv/acpbot/v/101419686 here at 14 seconds andn sometimes it's a green square) and bitrate skyrockets to 4-5k+ when I start moving with no movement prior.
I've reinstalled my OS , running an older Windows version (not the anniversary one) , reinstalled my drivers twice.

**Comment by Xaymar** [comment] 2016-11-16 16:38
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by alincupunct** [comment] 2016-11-16 16:44
Steps : 
1 - My hardware is supported.
2 - Everything is installed / updated.
3 - Read , done , still does the same.
4 - Read , been trying to fix it for a week , tested with a bunch of settings , literally does the same.
5 - I verified my configuration , again , been testing settings for a week , does the same with every single setting.
So here I am , reporting the issue.
What did I not follow?

**Comment by Xaymar** [comment] 2016-11-16 16:46
The final step.

**Comment by alincupunct** [comment] 2016-11-16 16:58
Step 5?
If so  , today I just loaded OBS on a clean W10 install and it does that.
If the "report an issue" step , the only thing that I didn't follow is this : 
"If you do include Videos, make sure it is the raw file uploaded to MediaFire, Mega or another free hoster. YouTube, Twitch, HitBox and similar VoDs are usually recompressed and remuxed, so they do not reflect the original output by the plugin."
No reason to RECORD it , because it does the same artifacting.

**Comment by Xaymar** [comment] 2016-11-16 16:58
> If you do include Videos, make sure it is the raw file uploaded to MediaFire, Mega or another free hoster. YouTube, Twitch, HitBox and similar VoDs are usually recompressed and remuxed, so they do not reflect the original output by the plugin.

I'm gonna need the files.

**Comment by alincupunct** [comment] 2016-11-16 17:10
https://www.youtube.com/watch?v=sb2W_4kai9Q&feature=youtu.be There's the video , the exact same settings.

**Comment by Xaymar** [comment] 2016-11-16 17:14
Please read again what the quoted text says and then upload _the raw file to a free hoster_.

**Comment by alincupunct** [comment] 2016-11-16 17:17
http://s.go.ro/4kuckcfn

**Comment by Xaymar** [comment] 2016-11-16 18:01
That wasn't too hard now, was it? Now I can actually tell you what's happening and why shit's broken.

## First, a look at the file:
- Resolution: 1920x1080, 16:9
- Profile: Main 4.1
- Bitrate: 1894 kbit/s
- Framerate: Variable 18.943 (Min 0.576, Max 30.303)
- Length: 2:49

## Next the log:

### System Properties
- Host Memory Type
- Surface Format: NV12
- Color Profile: .601 Partial

### Static Properties
- Resolution: 1920x1080, 16:9
- Framerate: 30000/1001 (~29.97)
- Quality Preset: Quality
- Profile: Main 4.1

### Dynamic Properties
- Rate Control Method: CBR
- Target Bitrate: 3000kbit/s
- Min QP: 0
- Max QP: 51
- VBV Buffer Size: 503935 bits 
- VBV Buffer Fullness: 100%
- Filler Data: Enabled
- Keyframe Interval: 2 seconds

### OBS Output
- 6445 frames encoded, 6445 frames drawn
- Total Time Encoded: 03m 35s 048ms 166µs ~667ns

## Analysis, Problems and Solutions

There are several issues with the file and the setup:
1. The log file is incomplete, some log lines are missing.
2. Using OBS 32-bit on a 64-bit system.
3. Output Bitrate is not even close to the Target Bitrate, at points it drops below 290kbit/s and it other areas it spikes to just 2100kbit/s.
4. Target Bitrate is too low for a 1920x1080x29.97 stream, 3500 or higher is highly recommended here - alternatively lower the resolution to 1280x720.
5. VBV Buffer is insanely strict, start with 0% and work up from there instead.
6. It looks like OBS wasn't running with administrator privileges and highest process priority. This has negative effects like variable framerate.

**Comment by alincupunct** [comment] 2016-11-16 18:12
1 - I just pressed upload current log from OBS.
2 - Is this that big of an issue?
3 - How can I fix that , though ? I just pressed the Twitch preset and while not much is going on , it goes down to 400-500 bitrate and when I start moving it jumps to insane bitrates while streaming.
4 - I was just testing it on 1080p , the same bitrate yields the same results on 720p.
5 - Should 0% VBV Buffer fix these insane bitrate jumps?

**Comment by Xaymar** [comment] 2016-11-16 18:18
1. Yes, 64-bit has more memory available for queueing frames.
2. 0% should help

Also make sure that OBS is running with administrator privileges and has the highest process priority.

**Comment by alincupunct** [comment] 2016-11-16 18:49
Went to 64-bit , ran it as administrator , downscaled to 720p and set VBV Buffer to 0% , started streaming , same bitrate behavior and artifacting (on stream , didn't do a recording test after since it crashed) in the client and as soon as the game capture kicked in OBS crashed.
Here's the crash log : http://pastebin.com/4RUdb3qk
Edit : Will be going to sleep now , more testing tomorrow.

**Comment by Xaymar** [comment] 2016-11-16 19:21
Crash in atiumd6a.dll, that's already been reported by #143 and #144. Should be fixed in the next driver update or the one after that.

**Comment by Xaymar** [comment] 2016-11-16 19:53
It's possible that for your GPU and use case you've hit GPU limits or that your driver is corrupt. The FAQ contains a guide on how to get a proper clean driver install in the event that that happened. (Always restart after install/uninstall of a driver.)

If you want to test the limits for your GPU, I've uploaded a tool for that here: http://cdn.xaymar.com/private/2016/11/VCESpeedTest_2016-11-16.7z

**Comment by Xaymar** [comment] 2016-11-16 20:05
The FAQ entry mentioned above: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-the-encoder-is-ignoring-my-settings

**Comment by alincupunct** [comment] 2016-11-17 08:00
1280x720 log - http://pastebin.com/pDsYyYWP
1920x1080 log - http://pastebin.com/j3YGazPC

As for the clean install , I did it and still the same behavior.
OBS crashed 2 times in a row right as game capture kicked in , once for League of Legends and once for CS:GO.

**Comment by alincupunct** [comment] 2016-11-17 09:51
It didn't use to do this on 16.9.2 (or if it did , I never noticed it.)

**Comment by Xaymar** [comment] 2016-11-18 02:54
Update to 16.11.4 and see if it fixes the crash.

**Comment by alincupunct** [comment] 2016-11-18 09:30
Should I do a clean install again , or will DDU be fine?

**Comment by alincupunct** [comment] 2016-11-18 12:24
So I upgraded at first , then I did a full clean install.
The crashes are gone (they were gone by just upgrading) , but bitrate still goes to shit when there's nothing happening on screen and skyrockets when movement happens.

**Comment by alincupunct** [comment] 2016-11-18 16:06
I updated to 1.4.2.3 , same behavior , do you want me to make a recording + log?

**Comment by Xaymar** [comment] 2016-11-18 17:03
I can't seem to reproduce this. At the beginning (~16-17 seconds) the encoder is slightly above or below the target bitrate, but after that it always stays at the bitrate.

**Comment by alincupunct** [comment] 2016-11-18 17:10
I reinstalled OBS , updated the plugin , bitrate's just fine now while I'm in game but in the client it still goes as low as 1000 , but the artifacting still happens on stream.

**Comment by Xaymar** [comment] 2016-11-18 17:12
Log file?

**Comment by alincupunct** [comment] 2016-11-18 17:12
Should I do it while streaming or recording?

**Comment by Xaymar** [comment] 2016-11-18 17:12
Shouldn't matter, streaming will show if it's your connection though.

**Comment by alincupunct** [comment] 2016-11-18 17:14
It's not , I tested with that tool that people provided on the OBS forums and I've got 100% quality connection with over 10k bitrate available to almost every european server.
I'll do it in a recording , coming up in a few minutes.
E: I'll do it while streaming actually.

**Comment by alincupunct** [comment] 2016-11-18 17:23
Here's the log file : https://gist.github.com/624a4ef230fafbc775c006f78b1dddd7
Here's the VOD if it helps : https://www.twitch.tv/acpbot/v/101826922

I've seen different behavior to what happens on Twitch on different systems/browsers.
For example a friend running a 4590 and a 760 just sees micro freezes on Chrome and Firefox while a second system in the house running a FX 8300 and a R7 270 gets the frame replayed (it spazzes out like crazy) on Chrome and Edge , while on my system (i5 3330 R7 260x) I get artifacting on Chrome and the micro freezes on Firefox.

**Comment by Xaymar** [comment] 2016-11-18 17:25
```
19:18:55.749: Output 'adv_stream': Total encoded frames: 6472
19:18:55.749: Output 'adv_stream': Total drawn frames: 6472
```

Log shows no dropped frames or repeated frames. Please upload one in which you are streaming.

**Comment by alincupunct** [comment] 2016-11-18 17:26
I was streaming , linked you the VOD.
It's spazzing the hell out on the livestream / VOD.

-- DOUBLEPOST EDIT --
Again , different behavior on different browsers.
On Chrome I get pink lines / green lines / artifacting.
On Firefox I get freezes.
On my phone app I get freezes.

**Comment by alincupunct** [comment] 2016-11-18 17:29
Again , different behavior on different browsers.
On Chrome I get pink lines / green lines / artifacting.
On Firefox I get freezes.
On my phone app I get freezes.

**Comment by Xaymar** [comment] 2016-11-18 17:36
I can only repeat what I said before, there are no frame drops or repeated frames in any of the logs you posted. It always encoded the exact same amount of frames that OBS sent to it.

I have seen Game Capture attempt to rehook "League of Legends.exe" multiple times during the VOD and that's it. The times it didn't do that the gameplay was smooth.

```
19:16:09.146: [game-capture: 'League'] attempting to hook process: League of Legends.exe
19:16:09.147: [game-capture: 'League'] using helper (compatibility hook)
19:16:13.184: [game-capture: 'League'] attempting to hook process: League of Legends.exe
19:16:13.185: [game-capture: 'League'] using helper (compatibility hook)
19:16:17.222: [game-capture: 'League'] attempting to hook process: League of Legends.exe
19:16:17.222: [game-capture: 'League'] using helper (compatibility hook)
19:16:21.258: [game-capture: 'League'] attempting to hook process: League of Legends.exe
19:16:21.258: [game-capture: 'League'] using helper (compatibility hook)
19:16:22.017: [game-capture: 'League'] Hooked to process: League of Legends.exe
19:16:22.017: [game-capture: 'League'] (half life scientist) everything..  seems to be in order
19:18:03.761: [game-capture: 'League'] attempting to hook process: League of Legends.exe
19:18:03.762: [game-capture: 'League'] using helper (compatibility hook)
19:18:07.798: [game-capture: 'League'] attempting to hook process: League of Legends.exe
19:18:07.799: [game-capture: 'League'] using helper (compatibility hook)
19:18:11.836: [game-capture: 'League'] attempting to hook process: League of Legends.exe
19:18:11.837: [game-capture: 'League'] using helper (compatibility hook)
19:18:15.648: [game-capture: 'League'] Hooked to process: League of Legends.exe
19:18:15.648: [game-capture: 'League'] (half life scientist) everything..  seems to be in order
```

I have also tried watching the VOD with different browsers now:
- Chrome: No issues, video debugger shows ~30 fps being rendered.
- Firefox: No issues.
- Opera: No issues.
- Internet Explorer: No issues
- Edge: No issues.

**Comment by Xaymar** [comment] 2016-11-18 17:41
All signs point to your system being too weak to handle streaming/recording with OBS while also gaming.

**Comment by alincupunct** [comment] 2016-11-18 17:42
Yet I can do x264 720p30fps no problem.

**Closed as completed** 2016-11-18 17:41 UTC
Labels: status:user error, type:support

**Comment by Xaymar** [comment] 2016-11-18 17:43
I strongly doubt that, otherwise you wouldn't be using hardware encoding.

**Comment by alincupunct** [comment] 2016-11-18 18:02
I will link a vod including task manager load to you on Steam.
It's fine though , your plugin was working fine for me on release , now it's shitting the bed , yet it's my system's fault , not your programming's.
This is why you'll not make it far in the programming world , keep blaming user's systems , not your dodgy programming.

**Comment by Xaymar** [comment] 2016-11-18 18:06
Yeah yeah. Because I totally changed anything that could have caused this.

**Comment by Xaymar** [comment] 2016-11-18 19:33
Public shaming time: 

![image](https://cloud.githubusercontent.com/assets/437395/20443706/3cde880c-adce-11e6-9902-7c9bf2296079.png)

Sorry @jp9000, I tried to be positive to this guy. But his LoL-player behaviour is clearly visible.

**Comment by Xaymar** [comment] 2016-11-22 16:01
![image](https://cloud.githubusercontent.com/assets/437395/20530927/49c7c88a-b0d5-11e6-81e3-5ab850a3c4d0.png)

You'd think this guy would have given up already.
