### ISSUE TITLE
RX 470: "High Quality" setting and upwards recording fails

### ISSUE THREAD

**Issue by fyrak1s** [Xaymar/OBS-AMD-Advanced-Media-Framework#136] opened 2016-11-05 18:00 UTC
Recording using the "Standard" as well as the "Recording" setting works well.
However when I try any setting like "High Quality" and upwards, the recording does not work at all. Here's the logs:

https://gist.githubusercontent.com/Nuc1eoN/ae08958d929845674b7866c0b55a2ef3/raw/e6e1415cf3853722c39d3b7f6850aa0a015aa5d9/obs-log

EDIT: Looks like there's someone with the same issue: https://obsproject.com/forum/threads/cannot-start-recording-in-0-16-4-using-amd-amf-plugin.57269/
Looks like he has got an AMD Radeon R9 200 Series card though..

**Comment by Xaymar** [comment] 2016-11-05 18:11
Duplicate of #135, #134

**Closed as completed by Xaymar** 2016-11-05 18:11 UTC
Labels: type:duplicate, status:solved

**Comment by fyrak1s** [comment] 2016-11-05 18:42
Thanks for the fix @Xaymar :)
