### ISSUE TITLE
amd not coming on obs encoder???

### ISSUE THREAD

**Issue by hus12345** [Xaymar/OBS-AMD-Advanced-Media-Framework#259] opened 2017-06-17 16:46 UTC
i downloaded all the programs i put the plugins into 64 and 32 whatever and i open obs and my amd is still not in encoder please help ive been up for 2 days trying to fix this :(  i have a radeon 8470 hd graphics card

**Comment by Xaymar** [comment] 2017-06-17 16:47
Duplicate of #258.

**Closed as completed** 2017-06-17 16:47 UTC
Labels: type:duplicate
