### ISSUE TITLE
Screen artifacts with pre7

### ISSUE THREAD

**Issue by sh1ny** [Xaymar/OBS-AMD-Advanced-Media-Framework#71] opened 2016-09-03 21:01 UTC
As i reported on the forum:

https://www.twitch.tv/bgshiny/v/87384175

This is what i get with pre7, downgrading to pre5 fixes things.

Here's the logs from when it happened :

[2016-09-03 21-57-47.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/453627/2016-09-03.21-57-47.txt)
[2016-09-03 23-27-59.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/453624/2016-09-03.23-27-59.txt)
[2016-09-03 23-29-35.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/453626/2016-09-03.23-29-35.txt)
[2016-09-03 19-24-51.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/453625/2016-09-03.19-24-51.txt)

My specs :

[DESKTOP-UOARCO8.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/453630/DESKTOP-UOARCO8.txt)

**Comment by Xaymar** [comment] 2016-09-03 21:16
Enable Debug Tracing and upload a log with that enabled too :3

**Comment by sh1ny** [comment] 2016-09-03 21:22
I just tried with your settings from here:

https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/issues/61#issuecomment-242947948

And it works ?

I used simple mode before. Here's with the advanced settings:

https://www.twitch.tv/bgshiny/v/87409840

**Comment by Xaymar** [comment] 2016-09-03 23:06
I just tried 1.3.0pre7 and have not received any of these artifacts with either the Constant QP settings in #61 or the Twitch preset. I'm not sure if this is even reproduceable at all :/

**Comment by Xaymar** [comment] 2016-09-04 07:15
Apparently these happen when you turn off Deblocking Filter, which doesn't make any sense. I have forwarded this and other reports to AMD for comment.

**Comment by Xaymar** [comment] 2016-09-05 12:29
Discovered a potential cause of this, see https://obsproject.com/mantis/view.php?id=614

**Comment by Xaymar** [comment] 2016-09-07 01:09
1.3.0pre8 should fix this, please report back.

**Comment by locodicegr** [comment] 2016-09-07 09:35
screen artifacts with pre8, all my recording file was with artifacts...pre7 was working good.

[2016-09-07 12-35-15.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/458756/2016-09-07.12-35-15.txt)
[2016-09-07 12-26-29.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/458757/2016-09-07.12-26-29.txt)

**Comment by Xaymar** [comment] 2016-09-07 10:37
@locodicegr Mind sharing the recorded file? Visible artifacts are near impossible to reproduce with just a log file.

**Comment by locodicegr** [comment] 2016-09-07 12:59
https://youtu.be/7XEJWZ8RcUw   -- pre7

https://youtu.be/EABqZ9sfF7M    -- pre8 

i just upload them, it will take some time for the quality
but you will get the idea.

**Comment by Xaymar** [comment] 2016-09-07 13:08
I meant the raw files - I can't download raw files from youtube since it re-encodes.

**Comment by locodicegr** [comment] 2016-09-07 13:12
@Xaymar 

Reinstall obs & pre8 :

[2016-09-07 16-25-06.zip](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/459222/2016-09-07.16-25-06.zip)

*FIXED by changing to MKV format...i had mp4!

@sh1ny try the mkv format.

**Comment by Xaymar** [comment] 2016-09-07 16:07
Seems like mp4 doesn't like PTS and DTS being different or something like that. I'll have to experiment with that a bit.

**Comment by Xaymar** [comment] 2016-09-07 16:56
Can't reproduce this anymore with the current commit at this time. Seems to be fixed now - expect it to be in 1.3.0rc1.

**Closed as completed by Xaymar** 2016-09-07 16:56 UTC
Labels: type:bug, status:solved
