### ISSUE TITLE
VCE 1.0 GPU recording with 1080p 60FPS got framerate drop

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#167] opened 2016-12-03 06:59 UTC
Unknown issue since the log file doesn't report encoder overloaded or drop frame.
VCE 1.0 GPUs are capable of recording 1080p 60FPS with Speed and Balanced quality preset but somehow my video got shutter.
[2016-12-03 10-41-53.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/628739/2016-12-03.10-41-53.zip)

**Comment by Xaymar** [comment] 2016-12-03 08:47
`10:42:00.822: [AMF Encoder] View Mode 'Master' is active, avoid giving anything but basic support. Error is most likely caused by user settings themselves.`

Closing.

**Closed as completed by Xaymar** 2016-12-03 08:47 UTC
Labels: status:user error, type:support
