### ISSUE TITLE
OBS doesn't start recording when Constant QP is selected

### ISSUE THREAD

**Issue by SkyLionx** [Xaymar/OBS-AMD-Advanced-Media-Framework#135] opened 2016-11-05 11:13 UTC
OBS Version: 0.16.4
AMF version: 1.4.1.0
AMD driver version: 16.11.2
CPU: i5-4440
GPU: R9 380 4GB

Log: https://gist.github.com/df5b82ef9286a754ff206e756466039e

When I select Constant QP as Rate Control Method, the recording doesn't start. If I select any other method it works. Every preset that involves CQP doesn't work either. (They work fine in 1.3.3.1)

**Comment by max20091** [comment] 2016-11-05 12:13
@Xaymar said he fixed the problem in the next version #134

**Comment by Xaymar** [comment] 2016-11-05 12:34
Yup, the problem is already fixed in the repository. 247bbdc40b1072333414fbca37c733acee60f763 is the commit that fixed it.

**Closed as completed** 2016-11-05 12:34 UTC
Labels: type:duplicate, status:solved
