### ISSUE TITLE
AMD encoder still not detected

### ISSUE THREAD

**Issue by orkprof** [Xaymar/OBS-AMD-Advanced-Media-Framework#324] opened 2018-06-24 23:06 UTC
With reference to my previous issue ( https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/313 ), the problem presented itself again after I perfmormed a full uninstall/reinstall of AMD drivers.

MY SPECS:
Operating System
	Windows 10 Home 64-bit
CPU
	AMD A8-9600	61 °C
	Bristol Ridge 28nm Technology
RAM
	12,0GB Dual-Channel Unknown @ 931MHz (13-13-13-31)
Motherboard
	HP 81FA (Socket FP4)
Graphics
	Generic PnP Monitor (1366x768@60Hz)
	512MB ATI AMD Radeon R5 Graphics (HP)	60 °C
	2048MB ATI AMD Radeon R7 M340 (HP)
	CrossFire Disabled
Storage
	931GB Hitachi HGST HTS541010A9E680 (SATA)	33 °C
Optical Drives
	hp DVDRW GUD1N
Audio
	Realtek High Definition Audio

With reference to the Troubleshooting guide:
1. Is your Hardware supported?
    Yes it is: it used to work till yesterday.

2. Do you have the latest Updates installed?
    Visual Studio 2015 Redistributables: already installed
    AMD Graphics Driver: latest drivers recently re-installed, downloaded directly from AMD website
    Open Broadcaster Software Studio: version 21.1.0 installed
    AMD Advanced Media Framework Plugin: version 2.3.3 recently re-installed

3. Have you read through the Frequently Asked Questions?
    Yes I have, couldn't solve my problem.

4. Did you check the Issue Tracker for similar Issues?
    Yes, I did.

5. Verify that your Configuration works with your GPU!
    I tried the thing which *apparently* made it work last time, didn't work. I honestly don't know what else to do or where else to look.

[2018-06-25 01-02-17.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/2131293/2018-06-25.01-02-17.txt)

**Comment by Xaymar** [comment] 2018-06-25 00:26
> 01:02:21.375: [AMF] A critical error occured during AMF Testing.

Your Driver or the AMF Runtime caused a crash during testing the encoder, thus it was disabled. This crash can have many reasons, from incompatible drivers down to actually broken hardware.

There is not much I can do for you here unfortunately, finding a fix that works on your system falls to you. Try as many drivers as you can, going back from the latest optional. Most importantly: Uninstall drivers using Display Driver Uninstaller in Safe Mode!

**Comment by orkprof** [comment] 2018-06-25 12:15
The issue presented itself after I uninstalled/reinstalled the AMD drivers and the AMD encoder. The latter was uninstalled through its own uninstaller, for the former I did in fact use DDU in safe mode.

Before this, the AMD encoder was easily detected by OBS Studio, provided I'd launch a game first.
This would only occasionally fail, but after shutting down OBS a re-opening it (with said game still running), the AMD encoder would successfully show up.

So I suppose the AMF Runtime used to crash back then, too, but only occasionally.The only thing that changed are the AMD drivers, although they should be the same version as they were when I opened #313. I'll try updating them through Windows Device Manager once again and see if anyhting changes.

**Comment by orkprof** [comment] 2018-06-25 13:22
OK, that didn't work, for some reason.
But rummaging through other threads I found out this ( https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/318 ) and tried the same solution, that is, installing 1.2.0rc1.
Now OBS Studio is giving me not 1, but 2 AMD encoding options. LOL.

**Comment by orkprof** [comment] 2018-06-25 14:47
(EDIT: though 1.2.0rc1 is able to detect AMD, OBS won't be able to start streaming. I'm trying further versions of the AMD encoder, but anything between 1.2.0rc1 and the latest version either won't detect AMD or cause OBS to crash at launch)
[2018-06-25 16-38-15.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/2133563/2018-06-25.16-38-15.txt)

**Comment by Xaymar** [comment] 2018-06-26 08:42
> I'll try updating them through Windows Device Manager once again and see if anyhting changes.

You should _never_ download Drivers through Windows Update, always go for the hardware vendors actual drivers, which for AMD is [their own website](https://support.amd.com/en-us/download). Like I said before, try optional and stable, and if neither works, try an older version. You can easily find older driver versions by searching "AMD Driver X.X.X" in Google with X.X.X being the version you want (or look at Guru3D, they usually have the older ones archived).

> But rummaging through other threads I found out this ( #318 ) and tried the same solution, that is, installing 1.2.0rc1.

1.2.0rc1 is based on "AMD Media SDK", which no longer exists. It is purely still listed for people that have no option to update their drivers, such as on All-In-One laptops and computers.

> anything between 1.2.0rc1 and the latest version either won't detect AMD or cause OBS to crash at launch

That is because the issue is in the Driver, not the Encoder Interface. The OBS plugin does nothing more than loading the AMD AMF Runtime, try and initialize it, and if that succeeds, lists itself as available.

**Comment by Xaymar** [comment] 2018-09-12 04:23
Does this still happen? If not, I will close this issue as solved.

**Comment by GittyGipity** [comment] 2018-11-05 19:40
Hello,
I have tried over and over again but cant get it to work... Yes, I have a graphics card amd 2 gigabyte graphics card I have 16 gigs of computer ram. I have an i5 core, I do not have a gaming pc / computer. I downloaded all files installer etc. But it doesn't work help help help please!!!!!!!!

**Comment by Xaymar** [comment] 2018-11-06 02:20
@GittyGipity Please create your own issue and follow the template. Closing this issue as there has been no reply by OP.

**Closed as completed by Xaymar** 2018-11-06 02:20 UTC
Labels: type:support
