### ISSUE TITLE
'Enforce Streaming Service Settings' is always being applied even when recording

### ISSUE THREAD

**Issue by aquamacho** [Xaymar/OBS-AMD-Advanced-Media-Framework#228] opened 2017-04-21 16:38 UTC
I manage to do this bofore in version 1.9.9.6 i think.
If you change IDR Period to anything less than 60 (for me atleast), something happens and now IDR Period is set to 0 in the Plugin settings.
`18:58:41.224: [AMF] [H264]<Id: 5>     IDR Period: 0 Frames`
And with this i no longer have I-Frame flicker or anything flickering LOL.
Hovewer, i tested this before and this trick have negative element to it.
So this 120 IDR:
[2017-04-21 19-11-28.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/947636/2017-04-21.19-11-28.txt)
Desktop:
https://drive.google.com/open?id=0B8uCAZ74gXrRM1VaRkVIcjZPY2s
Valley: (notice how fps meter is distorted in the bottom right corner)
https://drive.google.com/open?id=0B8uCAZ74gXrReVYzakhfQ3NUTUU
This is 59 IDR in obs = 0 IDR in settings:
[2017-04-21 19-18-53.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/947655/2017-04-21.19-18-53.txt)
Desktop:
https://drive.google.com/open?id=0B8uCAZ74gXrRNDFTTm5ORHFQclE
Valley:
https://drive.google.com/open?id=0B8uCAZ74gXrReXRPX2ExdHRoYTg

System specs:
Windows 10 x64 (.138) \ 8.1
AMD Phenom II X6 1045T
MSI R7770 Power Edition 1GD5/OC (gcn 1.0) hooked up to main monitor
9600 GT Asus Magic HDMI second monitor.
8G ddr3 ram
asrock 970 extreme3 mobo.
Plugin ver - 2.0.0.0 - 1.9.9.6
Drivers 17.4.3 (ReLive is not installed).

Obs stuff: view mode master (only in this mode you can change IDR)
Resolution - 1920x1080
Preset: no preset
Pfofile: High
Quality - Balanced
Bitrate - 3500
Fps - 60
OpenCL Conversion is on
DX9 (Api do not matter i think)

**Comment by Benman2785** [comment] 2017-04-21 17:11
IDR Period was fixed with 2.0.0. -> now "0" uses KeyFrameIntervall -> this should fix most user errors ;)

**Comment by Benman2785** [comment] 2017-04-21 17:12
btw 1080p60 with 3500kbps looks shitty -> try 720p60 or 720p48 -> will look much better

**Comment by Benman2785** [comment] 2017-04-21 17:13
https://www.youtube.com/watch?v=xI98gaUJnck - 720p48 3500kbps - compare that to your streams

**Comment by aquamacho** [comment] 2017-04-21 17:14
i was doing 3500 just for better representation of whats happening, i usually stream with 20k bitrate at 1080@60. But thx. Noticed.

**Comment by Benman2785** [comment] 2017-04-21 17:15
20k stream? twitch-partner? or own server? ;)

**Comment by aquamacho** [comment] 2017-04-21 17:15
No, youtube.

**Comment by Benman2785** [comment] 2017-04-21 17:16
yt allows 20k? ever thought only 8k

**Comment by aquamacho** [comment] 2017-04-21 17:17
YT recommends 9k for 1080@60, but who cares what YT actually reccomends?
You can push whatever you want to YT, they will re-encode bitrate to recommended values.
Twitch do not allows you to go higher that 6k, any value above that will be considered as site abuse.

**Comment by aquamacho** [comment] 2017-04-21 17:23
**Benman2785**
> this should fix most user errors ;)

**aquamacho**
 

> This is not an issue!

i just wanned to leave this for some one who struggles with same thing as i am.
Wait a second, i had keyframe interval 2.0, this is = 120 IDR ? why i have no refreshes then?

**Comment by Xaymar** [comment] 2017-04-21 17:36
Seems like there's a bug with the IDR Period property, an IDR that is non-zero shouldn't be reported as 0.

**Comment by aquamacho** [comment] 2017-04-21 17:39
In previous versions of the plugin, i had a problem were i cannot change IDR values to what i wanna them to, they were always 120 frames.

**Comment by Xaymar** [comment] 2017-04-21 17:40
IDR Period was only ever used in Master view mode, otherwise Keyframe Interval (which is in seconds and accepts fractions of a second) was used.

**Comment by aquamacho** [comment] 2017-04-21 17:43
Can i make IDR = 0 with keyframe interval?
I mean, something is broken, but i love the way it is.
Btw, Is there any info about latency issue?

**Comment by Xaymar** [comment] 2017-04-21 17:53
No you can not, simply because an IDR Period of 0 is actually impossible to handle. An IDR Period of 0 means that there should never be an IDR frame on which OBS can stop the stream or recording, you get no ability to seek anywhere without loading the entire file up to that point, you lose any dynamic configuration ability (since these are bound by IDR frames), a single dropped frame corrupts the entire future of the stream for hours or longer, ...

As to why it logs the IDR Period as 0, I'm not entirely sure. I don't think I've seen this behaviour before either.

**Comment by aquamacho** [comment] 2017-04-21 17:59
> this trick have negative element to it

This is negative side of this what i was talking about, when i was testing this before i was unable to fast forward in player, thats why i was not reporting about this in the first place. I was thinking that i just broke something on my side. Dammit.

**Comment by aquamacho** [comment] 2017-04-21 18:04
I think i need donate to you my PC, so you can look better whats going on.
Or use Chrome Remote Desktop or something.
But, no i-flicker tho.

**Comment by aquamacho** [comment] 2017-04-21 18:27
But with this you can make your UI look like this after a while :D
![screenshot_1](https://cloud.githubusercontent.com/assets/23249682/25291049/2e02aece-26d9-11e7-9f4c-ee7731f49ad6.png)
https://drive.google.com/open?id=0B8uCAZ74gXrRUlM2a2FtblFYZjQ
YT is struggling to re-encode this piece of art :P only 360p.

**Comment by Benman2785** [comment] 2017-04-21 18:36
i dont have that problem with RX 480 (17.4.3)

[AMFenc_2.0.0._idr_+60_bug.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/948022/AMFenc_2.0.0._idr_.60_bug.txt)

http://benmanshafen.de/OBS/VCE/AMFenc_2.0.0._idr_+60_bug.flv <- "save as"

sry my server today is freakin slow

**Comment by aquamacho** [comment] 2017-04-21 18:41
**Benman2785** just go buy gcn 1.0 card, you will have much more fun in here.

**Comment by Xaymar** [comment] 2017-04-21 18:45
Why would we downgrade from a GCN4 card with massively higher VRAM and GPU power to a weak GCN1 card?

**Comment by Benman2785** [comment] 2017-04-21 18:50
aquamacho - i had GCN 1 card -> HD7970 (flashed to GHz-Edition) -> replaced it with my RX 480 8G Nitro+ OC and am pretty happy ;)

**Comment by aquamacho** [comment] 2017-04-21 19:04
That was a joke, of course GCN 4.0 is better. We can see it right here with freaking I-Flicker that decreasing quality of image by i dont even know by how % every second\value that i input.

**Comment by Benman2785** [comment] 2017-04-21 19:06
try IDR-Period of 1/5 fps or 1/4 fps -> u WONT be able to search trough the files (until uploaded to Youtube)

**Comment by aquamacho** [comment] 2017-04-21 19:18
`22:17:20.680: [AMF] [H264]<Id: 5>     IDR Period: 0 Frames`
I cannot input any value below 60.

**Comment by Benman2785** [comment] 2017-04-21 19:23
ah below 60 // set IDR = 0 and keyFrameInterval = 2.00 // if its not working -> set IDR Period 2x FPS (so if u have 30FPS u set 60 or if u have 60FPS u set 120 e.g.)

**Comment by aquamacho** [comment] 2017-04-21 19:25
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/228#issuecomment-296267558
This was with idr 0 and keyframe 2.00

> if its not working -> set IDR Period 2x FPS (so if u have 30FPS u set 60 or if u have 60FPS u set 120 e.g.)

And that will bring back I-Flicker.

**Comment by aquamacho** [comment] 2017-04-21 19:32
**Benman2785** do you have by any chance old https://obsproject.com/forum/threads/obs-branch-with-amd-vce-support.13996/ OBS with VCE Branch stored on your pc, so you can share a link of it?

**Comment by Benman2785** [comment] 2017-04-21 19:32
yeah - i can upload a version if u want

**Comment by aquamacho** [comment] 2017-04-21 19:33
Please, i will show you how it will look for me if i will change IDR to 10 or w/e.

**Comment by Benman2785** [comment] 2017-04-21 19:34
i know how it will look like - u will have more iframes and the quality will raise (not so much blockyness)

**Comment by Benman2785** [comment] 2017-04-21 19:35
http://benmanshafen.de/OBS/obsvce_2016-06-12_64bit.7z

**Comment by Benman2785** [comment] 2017-04-21 19:36
http://benmanshafen.de/downloads/OBS_0_657b_With_Browser_Installer.exe in case u need old obs

**Comment by aquamacho** [comment] 2017-04-21 19:37
What was last working driver that worked with old AMF? 15.7?
17.4.3 is not working with old OBS\amf
Will install 16.10.1 Whql - no go.
Trying 15.11 - nope. I think the Creators Update is what preventing old AMF from working for me.
![screenshot_1](https://cloud.githubusercontent.com/assets/23249682/25294241/f93b6ce0-26e6-11e7-95f1-62758508447a.png)

**Comment by Benman2785** [comment] 2017-04-21 19:41
16.4? not sure though -> but maybe @Xaymar knows

**Comment by aquamacho** [comment] 2017-04-21 20:07
Anyways, if i will set IDR to anything below 60 this what it will looks like:
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/25
Just check how looks 120 IDR from my video and amagine that it flickers 6 times more than with 120 IDR.
I dont want re-install windows once more just to show this. Or do i?

**Comment by aquamacho** [comment] 2017-04-21 20:23
**Xaymar**, i wanned to ask, are you running your system from Uefi (GPT) or MBR partition?
I was thinking about if there any difference between those two, if you need Uefi Gop bios for gpu to work with the OS (boot to the os).
Maybe that the reason why we have that latency issue? 🤔
Hell, why am i asking, need answer - just go test it.

**Comment by Xaymar** [comment] 2017-04-21 20:53
UEFI or MBR do not have any impact on how HW responds after the BIOS/UEFI hands over control to the OS.

**Comment by aquamacho** [comment] 2017-04-21 21:46
Well, if you need to test something im here.

**Comment by aquamacho** [comment] 2017-04-21 22:56
I wonder what can **MikhailAMD** say about this.

**Comment by Xaymar** [comment] 2017-04-22 23:01
@aquamacho Can you run the VCE Speed Test tool linked on the Hardware Support page and upload the resulting .txt files?

**Comment by aquamacho** [comment] 2017-04-22 23:31
Sure, one sec. But im now on windows 8.1 with 1.4.3.11 running host mode because i was getting encoder overload msgs on both DX11 and 9.

**Comment by aquamacho** [comment] 2017-04-22 23:37
Do you need both x32 and x64 results?

**Comment by Xaymar** [comment] 2017-04-22 23:37
Yes that would be great.

**Comment by Xaymar** [comment] 2017-04-22 23:38
Remember that both write to the same location so you have to run one, zip the results up and then run the other. Don't bother with H265, only Polaris supports it.

**Comment by aquamacho** [comment] 2017-04-22 23:40
Yup.

**Comment by aquamacho** [comment] 2017-04-22 23:50
x32
https://drive.google.com/open?id=0B8uCAZ74gXrRTGwzVGJ4b2NCQ0U
x64
https://drive.google.com/open?id=0B8uCAZ74gXrRaXUwTW44a1FoTVk

**Comment by Xaymar** [comment] 2017-04-23 00:03
No errors in the sample tool, so I wonder what is causing this IDR Period weirdness.

**Comment by aquamacho** [comment] 2017-04-23 00:09
I just checked 1.4.3.11, i cant change IDR from 120, whatever i choose (IDR or keyframe) its stays at 120.

**Comment by aquamacho** [comment] 2017-04-23 00:12
Oh wait, where in the log i can check IDR that was set?

**Comment by aquamacho** [comment] 2017-04-23 00:13
This ?
`03:10:57.701: [AMF Encoder] <Plugin::AMD::H264Encoder::SetIDRPeriod> Set to 30.`

**Comment by Xaymar** [comment] 2017-04-23 00:13
In the plugin the actual IDR is after `IDR Period: `. In the tool it's in the .bat file.

**Comment by aquamacho** [comment] 2017-04-23 00:14
I cannot find what an actual IDR is set to
[2017-04-23 03-10-53.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/949383/2017-04-23.03-10-53.txt)

**Comment by Xaymar** [comment] 2017-04-23 00:16
```
03:10:58.013: [AMF Encoder] <Plugin::AMD::H264Encoder::SetIDRPeriod> Set to 30.
...
03:10:58.014: [AMF Encoder] <Plugin::AMD::H264Encoder::SetIDRPeriod> Set to 120.
...
03:10:58.014: [AMF Encoder] Picture Control Properties: 
03:10:58.014: [AMF Encoder] <Plugin::AMD::H264Encoder::GetIDRPeriod> Value is 120.
03:10:58.014: [AMF Encoder]   IDR Period: 120 frames
03:10:58.014: [AMF Encoder]   B-Frame Pattern: N/A
```

You have the enforce streaming service settings checkbox set.

**Comment by aquamacho** [comment] 2017-04-23 00:19
Yes? i dont get it :D
Do i need to uncheck it?

**Comment by Xaymar** [comment] 2017-04-23 00:21
If you want OBS to continuously override your settings, then you can leave it checked. Otherwise, well, it'd be wise to uncheck that. As you are Recording i strongly suggest using the Recording tab for the settings, you will save yourself a lot of pain.

**Comment by aquamacho** [comment] 2017-04-23 00:25
Hmmm, i streaming every day, and only recording if i need to test something.
But yes, i think IDR Period is working as intended on 1.4.3.11, no 0 IDR. Getting I_Frame flicker 2 times per second with keyframe 0.50.
Edit: So with IDR working i can show to **Benman2785** how IDR 10 or 20 is looking for me :D

**Comment by aquamacho** [comment] 2017-04-23 00:34
hahaha, this is IDR set to 12.
https://drive.google.com/open?id=0B8uCAZ74gXrRNExuakpUUmVMWEU
i love this FPS meter
![screenshot_1](https://cloud.githubusercontent.com/assets/23249682/25309460/69918fd4-27d6-11e7-971e-28ba6dd45361.png)

**Comment by aquamacho** [comment] 2017-04-23 00:50
**Xaymar**, do you have any co-workers\testers that have gcn1.0 card?
And if yes, do they have same issue as i? (IDR = 0) and this stupid I-Flicker
Wait, h_ly S*, is **enforce streaming service settings** option makes OBS use recommended bitrate settings from like here?
https://support.google.com/youtube/answer/2853702?hl=en
is this rail life? i`ve been streaming this whole time 9k instead of 20??

**Comment by Xaymar** [comment] 2017-04-23 00:59
No I do not.

**Comment by aquamacho** [comment] 2017-04-23 01:02
Is there a way i can help with this in any way? not by sending to you my GPU (which is impossible)

**Comment by Xaymar** [comment] 2017-04-23 01:05
Unless you have coding skills and actually want to delve into AMF and all the encoding stuff, I doubt there's much you can do.

**Comment by aquamacho** [comment] 2017-04-23 01:16
> Unless you have coding skills

No, i do not have any coding skills whatsoever.

Only thing i can do, is install all necessary software and then let you use my machine for what ever you want.
Anyways, sorry for wasting your time, and as always thx for your hard work with this Plugin. <3

**Comment by Xaymar** [comment] 2017-05-15 01:03
Does this still happen with 2.1.3?

**Comment by SPIKEYPUP** [comment] 2017-05-23 10:33
I'm sorry to chime in so late on this topic but I've been facing the same issue, no matter what I set for I-P or IDR periods/intervals, the settings are not taking during creation of the encoding session, the periods and intervals all come out to 0 it appears.  I also noticed this error in my logs 
_02:41:36.941: [AMF Runtime] [02:41:36.914][ConvertToDriver] Error: ..\..\..\..\..\runtime\src\components\EncoderHEVC\DriverParameterAdapter.cpp(382):parameter vector type(2): is not matched_

This has been greatly affecting my ability to do local recording with HEVC because the seeking of the created files is either ridiculously taxing and slow, or in files larger than 300MB or so plus, it's virtually if not totally impossible to seek even 1 second ahead.  Otherwise the files will play correctly and look to be what they should in terms of quality, but I'm not so sure to be honest if its using all the settings or not. I've tested across a wide variety of settings and view modes from basic to master, all result in files that are unseekable.   Here is the log of the session and a screenshot of the Recording settings, I set everything to default/basic and only adjusted the QP to 18/22, I just started with 2.1.3 tonight, I will report back what I find about Recording H264 and Streaming H264.  The problem for me with Recording and HEVC however has been going on for some many versions to be honest, I think up to 2 or 4 versions before 2.0.0  H264 Streaming seems to be fine, but I'll wait for your take on this before I start testing everything.

On the bright side... OpenCL however and Asynch Q issues seems to have been fixed for me with 2.1.3

I've attached a logfile along with a screenshot of the Recording Tab settings, and a Debug of the Video itself.  I wasn't sure if I should open a new ticket or not, I apologize if I should have, I just figured this behavior seemed very close to the OP/Ticket Issue.  Thanks again for your time and effort!  :)

![hevc recording params](https://cloud.githubusercontent.com/assets/27184427/26350171/236f07cc-3f67-11e7-828f-dc29e40eb177.png)
[2017-05-23 03-07-12.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1021801/2017-05-23.03-07-12.txt)
[DEBUG MP4 FRM_HDR_ALL_2017-05-23 03-08-56.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1021812/DEBUG.MP4.FRM_HDR_ALL_2017-05-23.03-08-56.txt)

**Comment by Xaymar** [comment] 2017-05-23 16:37
HEVC has currently no support for I/P/B/Skip periods and IDR Period is handled differently. You can't have a Keyframe Interval smaller than 1 second due to GOP restrictions. Additionally seeking in HEVC has never been supported, this is a driver bug.

**Comment by SPIKEYPUP** [comment] 2017-05-23 18:51
I see, that makes good sense now.  Oddly though, however Relive does its encoding parameters gives me no problems on HEVC with amazing quality and near instant seeking even using MS Movies/TV App for playback, with less than 1% usage so I guess that means it is properly using the HW Decoder.  I usually will do Relive around 15-18Mbps for 1080P and it's very close to original quality.  Of course I'd much rather use OBS though for all my Streaming and Recording.    Anyway, I did try to utilize H264 and I'm still running into the issue, all those periods and numbers are being set or kept at 0 even when settings are set to basic/reset to default.    OK ... I literally just went through each setting and clicked apply to destroy and recreate everything after setting all encoder types to "defaults" via their respective default option or by manually setting them.  seems now H264 is working properly so that is good :)   I'll try to rework my HEVC settings then to be as default as possible and still workable since I am not familiar with the required structure or variance in the GOP as you mentioned vs. H264 etc..  Thanks for taking the time to respond.  PS>  I'm sure you already know of it, but if not- the tool I used to get the media info/structure data with can be found here and it is Opensource and shell/explorer integratable: https://mediaarea.net/en/MediaInfo/Screenshots

-Spikeypup

**Comment by Xaymar** [comment] 2017-05-23 19:45
Seeking in HEVC requires the following runtime changes:
- https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/86
- https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/63

The former enables differentiating between I and IDR frames and the latter integrates timestamps into the actual bitstream, which is what many players use to seek through the file. The timestamps in the format itself should already be correct as they are in frame increments and OBS handles writing those.

**Comment by aquamacho** [comment] 2017-05-24 15:32
**Xaymar**
> Does this still happen with 2.1.3?

Sorry for not responding.

`18:25:18.616: OBS 19.0.2 (64bit, windows)`
`18:25:19.713: [AMF] Version 2.1.5 loaded`
```
18:25:22.848: [AMF] [H264]<Id: 5>   Picture Control:
18:25:22.848: [AMF] [H264]<Id: 5>     Period:
18:25:22.848: [AMF] [H264]<Id: 5>       IDR: 0 Frames
```
if keyframe is set to less than 60 frames, anything above that works as intended.
![screenshot_1](https://cloud.githubusercontent.com/assets/23249682/26411690/277fac1a-40af-11e7-98dd-88398ddf1104.png)
[2017-05-24 18-25-18.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1026095/2017-05-24.18-25-18.txt)
I-frame madness is still present.

**Comment by max20091** [comment] 2017-05-24 16:43
Keyframe interval should be set as 0.50 instead of 0,50
So a I frame will be set every 0.5 secs instead of 50 secs
And also disable multi-threading as your CPU have 6 cores otherwise it will slow down encoder a lot

**Comment by aquamacho** [comment] 2017-05-24 19:24
> **max20091**
> 0.50 instead of 0,50

Wrong.
Its , by default + you can not input dot in there.

> And also disable multi-threading as your CPU have 6 cores otherwise it will slow down encoder a lot

Are you sure that with multi-threading off my old x6 1045t even when OC wil perform better than with it enabled?

**Comment by Xaymar** [comment] 2017-05-24 19:32
The , and . depends on the system locale as far as I'm aware. Additionally, multi-threading does perform worse on any system as it has additional synchronization overhead that single-threaded does not have. It will only help on CPUs that are really restricted when it comes to single cores and should be tested without first.

None of that is relevant to this issue though, except for the initial reply. The log file however is not complete, tick the "Debug" option in the encoder to make a full log out of it (this was implemented to reduce overhead when this logging is not needed).

**Comment by aquamacho** [comment] 2017-05-24 19:43
Again:
set 0,50 in obs
[2017-05-24 22-41-09.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1026867/2017-05-24.22-41-09.txt)
Im looking at logs and some of the lines says IDR 30 which is correct.
I will do a test recording to check if fast seeking is working in player.

**Comment by aquamacho** [comment] 2017-05-24 19:58
No, its 0 IDR in the test run, no seeking in vid.

At the end, why do we care? its gcn 1.0 which has broken I-Frames. I think that nobody is using 77XX series to record something "seriously" daily as i do, i think we can close this thread. There is no reason for AMD to fix something that is 4 years old anyways.
Im fine with 20k bitrate :D

**Comment by max20091** [comment] 2017-05-25 00:13
LOL, what? I still seeking normally here with my HD 7730, still generate a I frame every 59 P frame
Can u set 1 instead of 0,50? You don't need that accuracy if you doesn't use video editor
Edit: confirmed if set IDR lower than 1 will cause IDR set to 0 @Xaymar

**Comment by Xaymar** [comment] 2017-05-25 01:11
It's been confirmed for a long time that Keyframe Interval below 1 second somehow makes it 0. There's probably a check doing the wrong thing somewhere.

**Comment by Xaymar** [comment] 2017-05-25 02:51
A little look into the code with everyone interested into this issue:

```
	// Picture Control
	double_t framerate = (double_t)obsFPSnum / (double_t)obsFPSden;
	/// Keyframe Interval/Period
	{
		uint32_t idrperiod = static_cast<uint32_t>(obs_data_get_int(data, P_PERIOD_IDR_H265));
		if (idrperiod == 0) {
			double_t keyinterv = obs_data_get_double(data, P_INTERVAL_KEYFRAME);
			idrperiod = static_cast<uint32_t>(ceil((keyinterv * framerate)));
		}
		m_VideoEncoder->SetIDRPeriod(idrperiod);
	}
```

This is a part of enc-h264.cpp, the thing that you see handling all your input and showing immediate changes in the UI and sending it off to the encoder interface. There is only one bug here and that one is that I check for P_PERIOD_IDR_H265 instead of P_PERIOD_IDR_H264 which makes IDR Period in H264 completely broken and only Keyframe Interval works.

But nothing of that would cause an IDR Period of 0 if you follow the code logic and math. It calculates a fractional framerate, checks if the IDR Period is 0 and if it is uses the Keyframe Interval multiplied by the fractional framerate rounded up (which would always give at least 1 frame). That calculated IDR Period is then handed off to the HW. Lets continue into SetIDRPeriod then:

```
void Plugin::AMD::EncoderH264::SetIDRPeriod(uint32_t v) {
	AMFTRACECALL;

	AMF_RESULT res = m_AMFEncoder->SetProperty(AMF_VIDEO_ENCODER_IDR_PERIOD, (int64_t)v);
	if (res != AMF_OK) {
		QUICK_FORMAT_MESSAGE(errMsg, PREFIX "<" __FUNCTION_NAME__ "> Failed to set to %ld, error %ls (code %d)",
			m_UniqueId, v, m_AMF->GetTrace()->GetResultText(res), res);
		throw std::exception(errMsg.c_str());
	}
	m_PeriodIDR = v;
}
```

Nothing strange here either, unless type casting suddenly became aware of much more of its surroundings. It just straight up gives it over to AMF for handling and AMF doesn't actually error out. And the value we see in the log is what AMF gives us back - so the question is: Did AMF break it or did the plugin?

**Comment by Xaymar** [comment] 2017-05-25 03:08
Edit: Cancel that, i think i found the cause.

**Comment by Xaymar** [comment] 2017-05-25 03:15
```
05:14:37.809: [AMF] [H264]<Id: 7>   Picture Control:
05:14:37.809: [AMF] [H264]<Id: 7>     Period:
05:14:37.809: [AMF] [H264]<Id: 7>       IDR: 38 Frames
```

Fixed in upcoming version.

**Closed as completed** 2017-05-25 03:33 UTC
Labels: type:bug, status:solved
