### ISSUE TITLE
FEEDBACK: Crimson ReLive

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#174] opened 2016-12-08 19:38 UTC
i streamed with the new built-in solution and can tell -> we clearly need AMD AMF for OBS Studio

1. new solution doesnt provide proper settings for streaming in good quality
2. is only suitable for local recording in high or custom

Xaymars plugin provides better overall quality

**Comment by k0zyrev** [comment] 2016-12-08 19:54
>new solution doesnt provide proper settings for streaming in good quality

even if quality was great, this software is nowhere near to OBS featurewise. So yes, AMD AMF support for OBS is absolutely a must have feature.

**Comment by Benman2785** [comment] 2016-12-08 20:00
btw 1.4.3.2 doesnt work for me with new driver - please also test this

**Comment by Xaymar** [comment] 2016-12-08 20:05
Fully aware, 16.12.1 is not yet available for me. The page for it is a blank white.

**Comment by CKannas** [comment] 2016-12-08 20:16
@Xaymar just sent you a Dropbox link to Crimson ReLive.

**Comment by atrblizzard** [comment] 2016-12-09 16:37
Since I will refrain on opening a new issue on this as it is meant to provide feedback with the new Crimson driver and plugin update, I do have encountered a certain bug not present in pre-ReLive updates.

Any input that I get to record (window, game capture or even display), all of them have the margins cropped from all directions.

Current log on the issue: https://gist.github.com/anonymous/46351e33ad9485de21633a136867689f
Using the generic Recording preset in just in case.

**Comment by Xaymar** [comment] 2016-12-09 17:00
Your scene is set to 1920x1080 and the encoder too. The output should provide a near perfect 1920x1088 with a crop of 0,0,8,0 - making the output 1920x1080

**Comment by atrblizzard** [comment] 2016-12-09 17:18
The final output is 1920x1080, but the recorded input itself looks to be scaled and have its margin cut out, as demonstrated here: http://files.atrblizzard.com/sharex/2016-12-09%2019-14-52.mp4

**Edit:** Turns out it's an issue caused by Windows 10's media player, not OBS or the plugin. The new ReLive update must have affected it somehow.

Sorry about the confusion.

**Comment by Xaymar** [comment] 2016-12-09 18:29
Did you have a Game Capture that itself was scaled? The encoder doesn't do any scaling itself, it copies 1:1 what obs gives it.

**Comment by Virtix21** [comment] 2016-12-10 05:32
Seems to be working perfectly on the RX 480 with Game and Monitor capture.

Edit: Battlefield 1 is getting my terrible recording FPS, 20 or so at 1440p and 30 or so at 720p re-scaled.

**Comment by Xaymar** [comment] 2017-01-10 02:09
I'll close this now, since there has been little activity here.

**Closed as completed by Xaymar** 2017-01-10 02:09 UTC
Labels: type:feedback
