### ISSUE TITLE
Crowdin for Translation

### ISSUE THREAD

**Issue by nwgat** [Xaymar/OBS-AMD-Advanced-Media-Framework#59] opened 2016-08-27 13:31 UTC
Its free for open source projects
https://crowdin.com/page/tour
https://crowdin.com/page/open-source-project-setup-request

**Comment by Xaymar** [comment] 2016-08-27 16:02
It's possible that the strings will be added to the obs studio main crowdin with the bundling.

**Comment by kytos22** [comment] 2016-08-27 23:30
I don't personally think this is necessary as this isn't a very big project but hey it is useful.

**Comment by Xaymar** [comment] 2016-08-28 12:07
Keep in mind that CrowdIn costs money - or at least it seems like it. As soon as I created this project there it immediately went "Hey your trial is gonna run out soon, subscribe now!" and offered me a $19.99/mo plan.

The way it is right now is pretty good, there's no actual need for something that does exactly the same as what is currently already there.

**Comment by Xaymar** [comment] 2016-09-05 22:28
CrowdIn account was closed, seems like it's not free.

**Comment by max20091** [comment] 2016-09-06 00:24
This isn't big enough to use crowdIn so just translate at here and also close this issue too :D 
PS: CrowdIn isn't free also

**Comment by kytos22** [comment] 2016-09-06 07:06
It is free, the problem is there are commercial products involved(AMD), and they're not interested in this project. Isn't a big issue since we only (fortunately) have 1 locale file with a few lines.

**Comment by Xaymar** [comment] 2016-09-06 10:52
If it asks me to pay money, it is not free. If it's only free for some people, that's called non-free sponsoring.  Anyway, closing this as it's not worth it to discuss this platform - githubs PR work great.

**Closed as completed by Xaymar** 2016-09-06 10:52 UTC
Labels: type:question, status:wontfix
