### ISSUE TITLE
errors/crashes when streaming DX12?

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#356] opened 2019-01-25 09:34 UTC
hey, often when i try to stream DX12 Game "The Divison" it randomly crashes OBS
EDIT: also has crashed PC or only the GPU-driver

is there a know bug about it?

**Comment by Xaymar** [comment] 2019-01-25 15:25
This would be the wrong place to ask, try the OBS Support or OBS Bug Tracker.

**Comment by Benman2785** [comment] 2019-01-25 15:33
only happens with h264 AMF

**Comment by Xaymar** [comment] 2019-01-25 15:35
Without a crashlog or a dump file I can't confirm that this is caused by H.264 AMF.

**Comment by Benman2785** [comment] 2019-01-25 15:36
i will try to get one

**Comment by Benman2785** [comment] 2019-01-25 16:54
looks like it has to do with OpenCL Conversion and/or PrePass when enabled

**Comment by Xaymar** [comment] 2019-01-25 16:58
Well, without a Crash Log or a Dump File, this is not a valid issue with the plugin or OBS Studio.

**Comment by Benman2785** [comment] 2019-01-25 17:06
as i said - i am still testing - but each run take at least 20min

**Comment by Xaymar** [comment] 2019-01-27 21:52
Please provide the following until Wednesday:

- Log file(s) with obs started under `--verbose --unfiltered_log` and the debug option checked in AMF encoder.
- Crash log(s)
- Dump file(s)

The first two can be found in `%APPDATA%/obs-studio` on windows, crash logs are in `crashes`, while log files are in `logs`.

**Comment by Benman2785** [comment] 2019-01-27 22:13
looks like its a crash made by the division
it didnt happened now in 6 runs - so i stoped it
yet one crash was reported to Ubisoft

**Comment by Xaymar** [comment] 2019-01-28 09:42
So it is the same as #263, #283 and #312?

**Comment by Benman2785** [comment] 2019-01-28 09:54
well considering that its now new hardware it cant be system dependent

1st was FX-9590 + 8GB DDR3 + RX480 8G or RX580 4G
2nd is Ryzen 2600X + 16GB DDR4 + RX580 4G

maybe i push my GPU to hard with AMF and Gaming - yet i use FRTC to lower load on GPU...

**Comment by Xaymar** [comment] 2019-02-05 23:56
I'm unable to reproduce this behavior on my own system. Please provide obs crash dumps and crash logs.

To obtain a crash dump, instead of clicking ok on the crash dialog, open task manager, go to details, find obs##.exe, right click it, and click "Create Dump File". Now wait until the dialog appears that a dump was created, go to the path it shows, rar/7z/tar.gz the file and upload that. Now you can click OK in the OBS crash window, and then also upload the crash log.

**Comment by Benman2785** [comment] 2019-02-11 12:39
found the error - when DX12 and using GPU-MemTimings-1 from new driver it will crash all dx12 randomly with my card :/
edit: on RX480 and RX580 with other CPU i also did tweak the timings via bios - so dx12 is more picky than dx11 with timings

**Comment by Xaymar** [comment] 2019-02-11 17:22
So [overclocking](https://github.com/obsproject/obs-amd-encoder/wiki/Frequently-Asked-Questions#q-why-is-obs-studio-crashing-when-i-click-streamrecord) was the cause?

**Comment by Benman2785** [comment] 2019-02-28 16:45
correct

**Closed as completed** 2019-03-02 12:01 UTC
Labels: type:invalid, status:user error
