### ISSUE TITLE
Minor issues? within gui selection

### ISSUE THREAD

**Issue by wazerstar** [Xaymar/OBS-AMD-Advanced-Media-Framework#48] opened 2016-08-23 19:00 UTC
When selecting preset it does not show up which preset you have selected, just blank.

http://prntscr.com/c9hra7

Also Profile level only shows max 5.1. is 5.2 missing?

http://prntscr.com/c9hl1l

Hence translation files goes up to 5.2

**Comment by locodicegr** [comment] 2016-08-23 19:02
I can confirm the blank selection.

**Comment by nwgat** [comment] 2016-08-23 19:32
i too, its not that _critical_

**Comment by wazerstar** [comment] 2016-08-23 19:41
Hence why I wrote minor, tho arent we here to help test and make it the best plugin?

**Comment by nwgat** [comment] 2016-08-23 19:42
yep

**Comment by Ryzym** [comment] 2016-08-23 20:32
Yup same here. I think it's the same for everyone. Also, I'm not sure if it's an installation error, but in the Advanced Encoder, the [Profile Level selection locale seems wrong/broken.](https://i.imgur.com/NYhkjNt.png)

**Comment by hymccord** [comment] 2016-08-24 01:30
Advanced isn't quite done most likely. It was _just_ turned on.

**Comment by Xaymar** [comment] 2016-08-24 07:48
The Blank selection is not a bug, the Preset field merely sets up the parameters for you. If OBS Studio would stop calling the modified callback when it's just loading the parameters, I could make it display the currently selected one too.

The Profile Level drop down will **only go as high as your GPU supports**!

And as @InKahootz said, Advanced is not done, I just turned it back on so that I can work and test on it.

**Comment by Xaymar** [comment] 2016-08-26 09:33
Fixed this a few commits ago, closing now for tracking purposes.

**Closed as completed by Xaymar** 2016-08-26 09:33 UTC
Labels: type:invalid, status:wontfix
