### ISSUE TITLE
Encoder Overloaded on R9 280x

### ISSUE THREAD

**Issue by Saymite** [Xaymar/OBS-AMD-Advanced-Media-Framework#225] opened 2017-04-19 21:56 UTC
Since I updated to 2.0.0.0 I've been getting Encoder Overloaded on OBS , no matter what settings I'm using.
For reference previously I had been using the Indistinguishable preset.

Specs:
[Specs.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/938655/Specs.txt)

Log:
[Log.txt](https://gist.github.com/3fc36067e60d749a0496135d2d393f47)

Video (30 secs but it shows the dropped frames) :
[Video](https://drive.google.com/open?id=0B5SJu1SDpJNXQmNGU2VVOXFpTmc)

**Comment by Xaymar** [comment] 2017-04-19 22:03
`22:46:01.262: [AMF] View Mode 'Master' is active, avoid giving anything but basic support. Error is most likely caused by user settings themselves.`

Normally I instantly close issues that have a log line like this.

Anyway, the issue is that your Keyframe Interval is too low for Constant QP, your GPU is simply not able to push that much data to VRAM and then to RAM.

**Comment by Saymite** [comment] 2017-04-19 22:04
Oh sorry, I messed up!

I was testing stuff out, it still fails on any other setup, give me 1 min.

**Comment by Benman2785** [comment] 2017-04-19 22:04
reset encoder - set it properly again -> will work ;)

**Comment by Saymite** [comment] 2017-04-19 22:06
[Log](https://gist.github.com/82d187c754433dc0c09ed60b43552ec1)

[Video ](https://drive.google.com/open?id=0B5SJu1SDpJNXWGdRNW8wNGU5MEE)

If the issue still is Keyframe Interval is too low for Constant QP, why is it too low now but not on 1.9.9.6?

**Comment by Benman2785** [comment] 2017-04-19 22:10
keyframe interval was ignored before

ps ur log isnt complete & pls check "debug" and use --verbose --log_unfiltered

**Comment by Saymite** [comment] 2017-04-19 22:22
Where do I put the   --verbose --log_unfiltered ?

Any recommendations on what I should set Keyframe to?

**Comment by Benman2785** [comment] 2017-04-19 22:26
shortcut - "C:\your-path-to\OBS Studio\bin\64bit\obs64.exe" --verbose --log_unfiltered
![how2log](https://cloud.githubusercontent.com/assets/21282980/25204883/ec9edb12-255f-11e7-8361-9a83365ef1b0.jpg)

**Comment by Xaymar** [comment] 2017-04-19 22:30
> If the issue still is Keyframe Interval is too low for Constant QP, why is it too low now but not on 1.9.9.6?

Because the property names have changed. Also the difference between 1.9.9.6 and this is literally name fixes and guaranteeing that we actually return a frame from the encoder. So if you see encoding overloaded now that means that in the past it was also overloaded, but OBS didn't notice it.

**Comment by Saymite** [comment] 2017-04-19 22:36
> Because the property names have changed. Also the difference between 1.9.9.6 and this is literally name fixes and guaranteeing that we actually return a frame from the encoder. So if you see encoding overloaded now that means that in the past it was also overloaded, but OBS didn't notice it.

Wich is weird because I recorded alot of content without It being laggy in the recorded video.

[New log](https://gist.github.com/anonymous/3b3f818a8b5a65b946e1a12c6d5a0482)

[Video](https://drive.google.com/open?id=0B5SJu1SDpJNXQnBoQlRWUWV4bnc)

**Comment by Xaymar** [comment] 2017-04-19 22:41
You don't normally see the lag until it's too late and then it's usually just a single skipped frame - except in cases where it's massively overloaded.

**Comment by Saymite** [comment] 2017-04-19 22:46
> You don't normally see the lag until it's too late and then it's usually just a single skipped frame - except in cases where it's massively overloaded.

[Heres a video of a visually intese game being recoreded with the same preset but in 1.9.9.6](https://www.youtube.com/watch?v=QwIpOy5mSyM)

No stutter no lag, weird I might rollback to 1.9.9.6

**Comment by Xaymar** [comment] 2017-04-19 22:48
Your new log shows the following:

- A significant delay between first submission and the first output packet (31ms).
- That the HW Encoder was waiting for 2 frames before it returned anything - usually a sign of B-Pictures being enabled for unknown reasons, however the log states that they are off...

Example of the encoder lag: SubmitInput for frame 6 happened at 23:32:33.431, QueryOutput was finally done with it at 23:32:33:460. This indicates that your GPU took 29ms to encode a frame, far above the ideal situation. This delay seems to be continuously increasing, which is outside of the plugins control.

Edit: The delay between frames itself is 24ms on average. That is higher than it should be.

**Comment by Saymite** [comment] 2017-04-19 23:03
So I re-did a video with 1.9.9.6

[Log](https://gist.github.com/anonymous/2e682aa326bd7d62cff75c7c554595ca)

[Video (600+Mb seems this time it recorded without lag or stutter)](https://drive.google.com/open?id=0B5SJu1SDpJNXQVA2dUFVd0VoTjA)

**Comment by Xaymar** [comment] 2017-04-20 07:36
```
23:57:51.382: [AMF] SubmitInput: frame->pts(      32) TS(     19200000000) Duration(      -600000000)
23:57:51.382: [AMF] QueryOutput: frame->dts(      23) TS(     13800000000) Duration(      -600000000) frame->pts(      23) Size(          168480)
23:57:51.399: [AMF] SubmitInput: frame->pts(      33) TS(     19800000000) Duration(      -600000000)
23:57:51.415: [AMF] SubmitInput: frame->pts(      34) TS(     20400000000) Duration(      -600000000)
23:57:51.416: [AMF] QueryOutput: frame->dts(      24) TS(     14400000000) Duration(      -600000000) frame->pts(      24) Size(           97771)
23:57:51.433: [AMF] SubmitInput: frame->pts(      35) TS(     21000000000) Duration(      -600000000)
23:57:51.434: [AMF] QueryOutput: frame->dts(      25) TS(     15000000000) Duration(      -600000000) frame->pts(      25) Size(           74392)
23:57:51.449: [AMF] SubmitInput: frame->pts(      36) TS(     21600000000) Duration(      -600000000)
23:57:51.449: [AMF] QueryOutput: frame->dts(      26) TS(     15600000000) Duration(      -600000000) frame->pts(      26) Size(           79799)
23:57:51.466: [AMF] SubmitInput: frame->pts(      37) TS(     22200000000) Duration(      -600000000)
23:57:51.483: [AMF] SubmitInput: frame->pts(      38) TS(     22800000000) Duration(      -600000000)
23:57:51.483: [AMF] QueryOutput: frame->dts(      27) TS(     16200000000) Duration(      -600000000) frame->pts(      27) Size(          203281)
23:57:51.500: [AMF] SubmitInput: frame->pts(      39) TS(     23400000000) Duration(      -600000000)
23:57:51.500: [AMF] QueryOutput: frame->dts(      28) TS(     16800000000) Duration(      -600000000) frame->pts(      28) Size(          199061)
23:57:51.515: [AMF] SubmitInput: frame->pts(      40) TS(     24000000000) Duration(      -600000000)
23:57:51.533: [AMF] SubmitInput: frame->pts(      41) TS(     24600000000) Duration(      -600000000)
23:57:51.533: [AMF] QueryOutput: frame->dts(      29) TS(     17400000000) Duration(      -600000000) frame->pts(      29) Size(          174085)
23:57:51.549: [AMF] SubmitInput: frame->pts(      42) TS(     25200000000) Duration(      -600000000)
23:57:51.549: [AMF] QueryOutput: frame->dts(      30) TS(     18000000000) Duration(      -600000000) frame->pts(      30) Size(          188873)
23:57:51.565: [AMF] SubmitInput: frame->pts(      43) TS(     25800000000) Duration(      -600000000)
23:57:51.566: [AMF] QueryOutput: frame->dts(      31) TS(     18600000000) Duration(      -600000000) frame->pts(      31) Size(          254526)
23:57:51.584: [AMF] SubmitInput: frame->pts(      44) TS(     26400000000) Duration(      -600000000)
23:57:51.599: [AMF] SubmitInput: frame->pts(      45) TS(     27000000000) Duration(      -600000000)
23:57:51.600: [AMF] QueryOutput: frame->dts(      32) TS(     19200000000) Duration(      -600000000) frame->pts(      32) Size(          279506)
```

218ms latency. Your GPU was struggling in 1.9.9.6 too, you just didn't see it.

**Comment by Saymite** [comment] 2017-04-20 09:13
So why does one video look laggy and the other one look okay?

**Comment by Xaymar** [comment] 2017-04-20 09:23
Because one of them actually waits for the GPU to finish encoding, the other doesn't causing the recording to be cut off early.

**Comment by Xaymar** [comment] 2017-04-20 09:47
So to sum things up:

- Your GPU is waiting for a long time before it actually starts returning frames, this is abnormal and a sign of B-Pictures being enabled (log states disabled).
- There's a larger than normal encode time, a 280x should be able to do at most 77fps on 1080p Balanced.

Please try a fresh install (Uninstall with AMD setup and then use DDU) and report back, you are probably running a mixed driver that happened somehow.

**Comment by Saymite** [comment] 2017-04-20 12:38
Doing a fresh install worked (even tough I did a fresh install before)

Anyways Im still leaving two logs here to see if you can find anything wrong, thanks for the support so far, you're doing an amazing job.

[1.9.9.6 log](https://gist.githubusercontent.com/anonymous/0affa40549907dcbd70e6e64573f8871/raw/954c7af7eb936a58d488c70b31457da237fc624c/2017-04-20%252013-17-43.txt)
[1.9.9.6 Video
](https://drive.google.com/open?id=0B5SJu1SDpJNXdEljbnVGcl9UQUU)
[2.0.0.0 log](https://gist.githubusercontent.com/anonymous/f22e928698672086b009675c16096895/raw/d22c7b862630484741dd1487942426b56e147e57/2017-04-20%252013-29-10.txt)
[2.0.0.0 Video
](https://drive.google.com/open?id=0B5SJu1SDpJNXR184VjhHMTRNRVE)

**Comment by aquamacho** [comment] 2017-04-20 20:17
Okay, i will leave some feedback to, im getting "encoder overloaded msgs" with (Async Q & OpenCL Transfer) OpenCL Conversion however working great it seems. I will do drivers re-install like **Saymite** did before, and if nothing changed i will make new thread.
and yes, i know about:
`[AMF] View Mode 'Master' is active, avoid giving anything but basic support. Error is most likely caused by user settings`
> Normally I instantly close issues that have a log line like this.

How you will bug fix anything if we will not leave any feedback then?

**Comment by Xaymar** [comment] 2017-04-20 20:24
Async Queue is experimental. There is absolutely no need for you to use View Mode Master, end of story.

**Comment by Saymite** [comment] 2017-04-20 20:31
I just tested a lilte more and its not fixed...


Its like a 50/50 chance of working, if the Overload message shows up when I press record the whole video lags and is super choppy, however if it starts up normally and the overload is after that it just drops some frames

Im super confused

**Comment by aquamacho** [comment] 2017-04-20 20:52
What about OpenCL Transfer? this located in View mode Advanced

> There is absolutely no need for you to use View Mode Master

OpenCL Options is in "experimental" phase to? then excuse me please.

`end of story`

**Comment by Xaymar** [comment] 2017-04-20 21:14
Advanced is not Master. Edit: Also you literally only have to modify Basic properties, most of you do not have a valid reason to be using anything else anyway.

**Comment by aquamacho** [comment] 2017-04-20 21:25
> Advanced is not Master.

Gotcha.
No offence, but you only read up to the word "Async Q" and ignored the rest did you? :D
I feel i will get banned.
Edit: But OpenCL Transfer tho.

**Comment by Xaymar** [comment] 2017-04-20 21:34
No, I read the entire thing. The bug with Async Queue is known (#223), however it doesn't seem to be fixed easily (it's sleeping longer than it should under all circumstances). Also I don't ban unless you either really get on my nerves (aka start being want-but-do-nothing-kind) or start threatening me. :)

**Comment by aquamacho** [comment] 2017-04-20 21:52
Okay, serious stuff now, i`ve reinstalled driver and issue partially went off, or me changing to view mode Advanced helped. however Encoder Overloaded thing happens only in quick motion/action scenes

`00:39:33.591: device_duplicator_create: Failed to duplicate output (80070005)`

is only i see wrong.

[2017-04-21 00-46-34.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/945560/2017-04-21.00-46-34.txt)

Edit: Actually, why im only talking about bad stuff, im able to record (and hopefully stream) with DX11 without encoder overloaded msgs after 2.0.0 update.
Little bit offtopic, but what was the diff between Host mode and rest (exсept OpenGL - who cares)

**Comment by Xaymar** [comment] 2017-04-20 22:15
Seems like latency drastically increased for you. I haven't been able to reproduce anything like this, but this behaviour seems to be the same for many users now. I wonder what actually causes it, since it seems so random to me and people just now started getting the issue.

**Comment by aquamacho** [comment] 2017-04-20 22:18
I wonder if DX11 has same problem with latency.
Yep, DX11 has same latency.
[2017-04-21 01-20-31.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/945630/2017-04-21.01-20-31.txt)

**Comment by Xaymar** [comment] 2017-04-20 22:25
Less than what you are getting. 16-32ms are not normal...

**Comment by aquamacho** [comment] 2017-04-20 22:32
> I haven't been able to reproduce anything like this

I think you have better CPU\GPU\hardware. My 7770 is to old i think.
Are you on the latest drivers 17.4.3?
I have windows 8.1 embedded edition, mb i need switch to Win10 to, god pls no... i do not wanna waste another 8 - 10 hours if Win10 will have same problems....

**Comment by Xaymar** [comment] 2017-04-20 22:32
I'm on 17.4.3 with Creators Update, yes.

**Comment by aquamacho** [comment] 2017-04-20 22:41
i can tell **Saymite** was not running The Creators Update from the logs that he provided
`Windows Version: 10.0 Build 15063`
no... nvm... this is creators update, okay im gonna just yolo it, will fast like bullet install creators update and will report back, jesus help me.
Or mb im not.

**Comment by Xaymar** [comment] 2017-04-20 22:53
I'm actually on Version 1703 (OS Build 15063.138) which is Creators Update that you get early (before all drivers are WHQL).

**Comment by aquamacho** [comment] 2017-04-20 22:58
.138 ? I do not think i can get that version, im not insider, i have only 15063.0
Version 1703: 10.0.15063.138 
Public release: April 25, 2017
Well.... i will wait for april 25th then :D

**Comment by Xaymar** [comment] 2017-04-20 23:18
Huh, I'm not in Insider either. All i did was run the tool that upgrades you earlier to Windows 10 Creators Update.

**Comment by aquamacho** [comment] 2017-04-20 23:27
wait a second, the "tool" that you mentioned called windows update?
https://support.microsoft.com/en-au/help/4015583
you can install that by using windows update feature?

**Comment by Xaymar** [comment] 2017-04-20 23:30
Yeah

**Comment by aquamacho** [comment] 2017-04-21 01:15
So, im back. Win10 .138. (the OS is garbage as same as it was before Creators Update, except now its much slower)
From my perspective of view looks like nothing has changed, same around 16013455 ns. I will play some more with settings and see whats what.
[2017-04-21 04-04-35.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/945827/2017-04-21.04-04-35.txt)
Next thing that improoved with 2.0.0 is that recording stopping Instantly now. 
And H_ly Sh_t i can now record on Win10 with same performance as in Win 8.1 with DX11, Except this latency thingy.
Running OBS with Elevated Privileges do not help. 
Pre-pass mode (full) increases latency twice (expected). 58722450 ns
OpenCL Conversion does the same.
Я сдался -_-.

**Comment by Saymite** [comment] 2017-04-21 12:22
So, I have an intresting log now, I just tried recording my desktop and it overloaded from the start.

[Log](https://gist.githubusercontent.com/anonymous/c9dcbfc6f619f640981e26e90c358d08/raw/362a5ba3d4033bf62be5209b175c3bf6442a0431/2017-04-21%252008-16-45.txt)

Edit: just relized it wasnt even recording the desktop, just a black screen. What?

**Comment by Xaymar** [comment] 2017-05-14 14:16
@Saymite 

> Hello there, Xaymar first of all I want to thank you for developing this plugin.
> 
> The issue im reporting is still the same as #225 , but since you updated the plugin I wanted to test the new version out,you can go ahead and close #225 , so here goes nothing;
> 
> Specs:
> 
> https://hastebin.com/pujafezeco.sql
> 
> Short Version : R9 280X
> i5 4670
> 
> The issue: The Issue I am having is that I get "Encoder Overloaded" while trying to record something that worked before and is well within my cards capabilities, to add to that my videos become extremelly laggy, eg. 1 frame per 10 seconds, and pressing "Stop Recording" takes 1-2 mins and sometimes makes OBS just quit.
> This issue started to happen since 2.0.0.0+
> Before when I would get "Encoder Overloaded" my frames would go down but never this extremely.
> This is all on a fresh install of codecs + OBS + drivers, might try re-installing OS if problems cant be found.
> 
> Testing methadology:
> Run a benchmark in GTA V windowed mode.
> OBS settings : Using Indistinguishable Preset
> 
> 2.1.2 log:
> https://gist.githubusercontent.com/anonymous/8f9d9a7dcd6a998cc7233c75fa321081/raw/061d9b3a4594c595335e42bb3bb96e0b210cf4fb/2017-05-14%252013-40-36.txt
> 
> 2.1.2 video:
> https://www.youtube.com/watch?v=iAp0RK-Ql_Q&feature=youtu.be
> 
> 1.9.9.6 log:
> https://gist.githubusercontent.com/anonymous/3e1a946fff9eae89ea567e0b2bec91e7/raw/09a1bf273908b9cbb8fdf3592c68d31c845542eb/2017-05-14%252013-59-35.txt
> 
> 1.9.9.6 video:
> https://www.youtube.com/watch?v=LGBeaMUsaXA&feature=youtu.be

Next time, please follow the Troubleshooting Guide correctly. Especially step 4.

**Comment by Saymite** [comment] 2017-05-14 14:54
So sorry!
Anyhow, since you told me to reference to 1.2 RC1:

log:
https://gist.githubusercontent.com/anonymous/30e4e681726f957c7bc4f2d7a12131a0/raw/400eb825811f619066c9b5878d66db88599cb303/2017-05-14%252015-24-36.txt

video:
https://www.youtube.com/watch?v=KWiO5A-UchI&feature=youtu.be

**Comment by Xaymar** [comment] 2017-05-14 15:04
### 1.9.9.6:
> 13:59:49.036: [AMF] QueryOutput: frame->dts(      36) TS(     21600000000) Duration(      -600000000) frame->pts(      36) Size(             167)
> 13:59:49.052: [AMF] SubmitInput: frame->pts(      51) TS(     30600000000) Duration(      -600000000)
> 13:59:49.069: [AMF] <Id: 13> Submitting Surface failed , error AMF_INPUT_FULL (code 25)
> 13:59:49.069: [AMF] QueryOutput: frame->dts(      37) TS(     22200000000) Duration(      -600000000) frame->pts(      37) Size(             161)
> 13:59:49.085: [AMF] SubmitInput: frame->pts(      53) TS(     31800000000) Duration(      -600000000)
> 13:59:49.085: [AMF] QueryOutput: frame->dts(      38) TS(     22800000000) Duration(      -600000000) frame->pts(      38) Size(             175)

As you can clearly see in this log, this version didn't care what happened with the submitted frame - which about matched the behaviour from 1.4.3.11 and earlier. It just pushed it into a queue and did things later, resulting in drastically delayed encoding stops or in the case of it being so far delayed that another keyframe happens earlier it would actually cut the video early. Or might have even caused massive desynchronization eventually, ate all of your RAM for breakfast and so on.

### 2.1.2:
This log is actually showing the correct issue. Submitting the frame to the GPU already takes ~3 msec but encoding time is at about 23ms. This isn't abnormal, the problem can be explained by simply taking into account just how much the PCI-E bus is actually being used and how much the South&North-bridge are used.

I actually experience this myself and had to take some precautions as to reduce that effect now. Completely using all 8 SATA3 devices seems to cause significant impact on how long the transfer to and from the GPU takes.

> Anyhow, since you told me to reference to 1.2 RC1

I didn't tell you to use 1.2.0rc1, I said that the only thing you can (are allowed to, since it behaves almost identically) is that version. And that one shows a 5.8% rendering lag.

**Comment by Saymite** [comment] 2017-05-14 15:22
Alright, sorry for all the mess, :/
I reckon my solution is to use other encoding presets? 

Its weird that the 280x is "rated" for 77fps in balanced @1080p but I guess the Indistinguishable preset is too much, still odd that it "worked" before.

**Comment by Xaymar** [comment] 2017-05-14 15:32
> I reckon my solution is to use other encoding presets?

Probably.

> Its weird that the 280x is "rated" for 77fps in balanced @1080p but I guess the Indistinguishable preset is too much, still odd that it "worked" before.

If you mean the VCE1.0 entries on the wiki, those are explicitly stated on the page itself to be read as "up to <x> FPS". That means that those values represent the absolute maximum performance in a perfectly ideal situation. Unfortunately the perfect ideal situation is rarely if ever achieved, as it requires the frame to always be on the GPU ("GPU -> GPU encode -> Host" instead of "GPU -> Host -> GPU -> GPU encode -> Host") and requires that absolutely nothing else is using the system bus's (GPU, CPU, Northbridge, Southbridge, etc). It is almost impossible to get that situation during actual gaming. :(

For future reference, to get the true FPS that your card could be rated for you have to add an expected frame upload and packet download time to the frame latency. At 77 fps 1920x1080 pure GPU the frame latency is 12.987ms and the upload/download latency is ~3ms for either direction on your system, which results in a final latency of 18.987ms - and that is also a primarily the best situation.

**Comment by Xaymar** [comment] 2017-05-14 22:28
I have talked with Mikhail about the cause of this. Seems like their Power Management actively underclocks the chip if it isn't fully used, resulting in an encoding overloaded message. I have added a workaround for this to 2.1.3, so I will mark this as type:bug status:solved and close this with the next push.

**Comment by Saymite** [comment] 2017-05-14 22:40
Oh, that makes some sense, That probably explains why I couldnt record my desktop, wating for that new version, 
Thanks again!

**Comment by Xaymar** [comment] 2017-05-15 01:01
2.1.3 is out, check out the releases!

**Closed as completed by Xaymar** 2017-05-15 01:01 UTC
Labels: type:bug, status:solved
