### ISSUE TITLE
Failed to set to 4294966296, error AMF_OUT_OF_RANGE (code 5)

### ISSUE THREAD

**Issue by Sjunpei** [Xaymar/OBS-AMD-Advanced-Media-Framework#304] opened 2018-02-22 20:07 UTC
Error message 
Failed to start recording
Starting the output failed. Please check the log for details.

NOTE: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date.

drivers are up to date.  Downloaded old v20.1.3 and it records again.  Sending out both log files.

[2018-02-22 15-04-03.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1749385/2018-02-22.15-04-03.txt)

first one is with v20

[2018-02-22 14-05-17.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1749386/2018-02-22.14-05-17.txt)

second one is of version 21.  I could not send the obs-studio zip as it was too big.  If you need a specific folder let me know

**Comment by Xaymar** [comment] 2018-02-22 20:08
You can send the .zip file directly to info@xaymar.com.

**Comment by Sjunpei** [comment] 2018-02-22 20:10
the folder was like 38mb.  it wouldn't let me send it via email either

**Comment by Xaymar** [comment] 2018-02-22 20:13
You can significantly reduce the size by compressing as .7z and .rar, which 7-zip and WinRar can do. Alternatively, just include the obs-studio\basic directory, which should have all necessary content. Do not attach it here as the contents do have your stream key if you currently have set in any profile, instead send it via e-mail to info@xaymar.com.

**Comment by Xaymar** [comment] 2018-02-23 14:45
Looking at your profiles, it seems that the bitrate and keyint_sec are stuck at -1 for an unknown reason. The old "Bitrate.Target" property was straight up eaten and seems to no longer be in the profile, so I don't know what the old value should have been.

Thank you, this should help me figure out why this happens.

**Comment by Xaymar** [comment] 2018-02-24 03:54
Partially successful at reproducing this issue. The following steps will result in the "Bitrate.Target" entry missing from the profile:
- Run OBS Studio 19.x (AMF 2.1.6).
- Create a new profile.
- Set Output Mode to Advanced.
- Select AMD Encoding for Recording.
- Select Preset YouTube in the AMD Encoder settings.
- Save (Click OK).
- Close OBS Studio.

What's left to figure out is where the -1 comes from.

**Comment by Sjunpei** [comment] 2018-03-04 18:25
any luck in resolving the -1?  I've been using the previous version in the
meantime

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Xaymar** [comment] 2018-03-04 21:04
-1 is caused by an invalid value being stored instead of the correct one. You can easily fix it by setting the correct bitrate in the encoder settings again.

**Comment by ExecThTs** [comment] 2018-03-16 22:04
I'm also seeing this issue -- 
`[AMF] [H264]<Id: 6> <Plugin::AMD::EncoderH264::SetResolution> Failed to set to 2560x1080, error AMF_OUT_OF_RANGE (code 5)` occurs when I try to record.

Full log [here](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1820906/2018-03-16.22-53-02.txt).

**Comment by Xaymar** [comment] 2018-03-16 22:05
That is not the same issue. What you are experiencing is that you set the resolution too high for your GPU Encoder to encode. You likely have a GPU that is only capable of at most 1920x1920 (VCE2/GCN2 and earlier).

**Comment by ExecThTs** [comment] 2018-03-16 22:08
It's supposed to work, BandiCam can do it with the AMD APP Encoder, which is supposedly the same. The GPU is an R9 270 btw; if it can do that as a desktop resolution it should work for recording too, isn't it?

**Comment by Xaymar** [comment] 2018-03-16 22:13
Please open your own issue instead of using this one. Your issue is a different one and it's explained in the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting) under the Hardware Support section. Specifically the Video Coding Engine 1.0 section, which explicitly states the maximum supported resolution of these cards, which is 1920x1920. BandiCam is likely offloading to CPU or using another method, as the physical encoder can't do more than 1920x1920 as reported by people all over the world in the entire development of the plugin (and even AMD themselves).

**Comment by ExecThTs** [comment] 2018-03-16 22:19
I see. Thanks anyway!

**Comment by Xaymar** [comment] 2018-03-17 11:02
Version 2.3.3 fixes one of the causes for this issue, but the true cause is still unknown. Even deep investigation into the code didn't reveal any possible way for the value to suddenly end up at -1, since that would mean that something _before the Target Bitrate change_ wrote a -1 to the value. But that would also mean that that -1 should have been overwritten by the true Target Bitrate, but it didn't. Overall this doesn't really make any sense so far.

**Comment by Sjunpei** [comment] 2018-03-19 17:45
oh wow.  So should I be good to update to that version or should I hold off
for now until the cause is identified?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Xaymar** [comment] 2018-03-19 22:23
The cause is something to do with updating from 2.2.x and before to 2.3.x and after, since the bitrate property was internally renamed. This somehow causes it to store a -1 for some configurations, but so far I've only managed to reproduce one of the problems it actually brings.

It's safe to update if you have manually fixed the bitrate field, otherwise you will still run into the same issues as before.

**Comment by Sjunpei** [comment] 2018-03-20 13:09
I think I know, but just to be safe, where and how to I adjust this setting
manually?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Xaymar** [comment] 2018-03-22 15:44
It can be adjusted in the encoder settings for both simple and advanced. It is called "Bitrate" or "Target Bitrate" (possibly invisible with certain Rate Control Modes).

**Comment by Xaymar** [comment] 2018-04-21 12:27
I have to date been unable to reproduce this behavior. I'll close this as unfixable, as this seems to happen to very few people.

**Comment by Benman2785** [comment] 2018-04-21 13:04
just give it a try:

disable "high-dpi scaleing" and "Fullscreen optimizations" for the application you capture

**Closed as completed** 2018-04-21 17:26 UTC
Labels: type:bug, status:wontfix

**Comment by DonatasFe** [comment] 2019-03-26 20:27
> 
> 
> Partially successful at reproducing this issue. The following steps will result in the "Bitrate.Target" entry missing from the profile:
> 
>     * Run OBS Studio 19.x (AMF 2.1.6).
> 
>     * Create a new profile.
> 
>     * Set Output Mode to Advanced.
> 
>     * Select AMD Encoding for Recording.
> 
>     * Select Preset YouTube in the AMD Encoder settings.
> 
>     * Save (Click OK).
> 
>     * Close OBS Studio.
> 
> 
> What's left to figure out is where the -1 comes from.

works on OBS 23.0.2 with AMD R9 200 series
