### ISSUE TITLE
RX 480 full encoder Queue every time & high CPU load

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#150] opened 2016-11-19 17:35 UTC
GPU: Sapphire Nitro+ RX 480 8G OC
CPU: FX-8150 @4.2GHz
MoBo: GigaByte 990FX-Gaming
OBS 0.16.5 32bit
Plugin: 1.4.2.3
Driver: 16.11.4 Hotfix

every scene with some more movement result in "dropped frames" due to encoder queue full
tried a bunch of settings and twitch preset

instead of 4-6% cpu load on encoding i have 8-10% now

http://benmanshafen.de/streamdl/ -> here u find a bunch of raw-videos (stream recorded from stream-server) ;) (download is currently a little low - will be fixed soon)

**Comment by Xaymar** [comment] 2016-11-19 18:10
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Benman2785** [comment] 2016-11-20 16:59
changed

**Comment by Xaymar** [comment] 2016-11-20 17:02
Still missing log files

**Comment by Benman2785** [comment] 2016-11-21 13:50
[2016-11-21 14-31-31.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/603727/2016-11-21.14-31-31.txt)
http://benmanshafen.de/pics/OBS/Xaymar/2016-11-21_2014-31-31.flv (will be uploaded in 5min)

also FillerData is bugged again

**Comment by Benman2785** [comment] 2016-11-21 13:53
http://benmanshafen.de/pics/OBS/Xaymar/2016-11-21_14-31-31.flv
http://benmanshafen.de/pics/OBS/Xaymar/2016-11-21_14-31-31.txt
[2016-11-21 14-31-31.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/603740/2016-11-21.14-31-31.txt)

FillerData is still Bugged
noticed often 100% GPU-load without reason & much higher CPU-load for VCE
bad quality compared to older versions

also tried OBS 0.16.6 32bit

**Comment by Xaymar** [comment] 2016-11-21 13:55
`14:31:38.397: [AMF Encoder]   Coding Type: CALV`

Keep Coding Type at Default.

```
14:31:38.397: [AMF Encoder]     Minimum: 1
14:31:38.397: [AMF Encoder]     Maximum: 42
```

Max QP should be at 51.

`14:31:38.398: [AMF Encoder]     Size: 58333 bits`

VBV Buffer Strictness should not be at 100%, otherwise you will massively undershoot the Target Bitrate. Test with Filler Data off to see how low it gets.

```
14:31:38.398: [AMF Encoder]     Filler Data: Enabled
14:31:38.398: [AMF Encoder]     Frame Skipping: Disabled
14:31:38.398: [AMF Encoder]     Enforce HRD Restrictions: Disabled
```

Enable Frame Skipping and also test with Enforce HRD Restrictions active.

**Comment by Benman2785** [comment] 2016-11-21 13:56
as i said i tried it with your twitch preset -> same problem

also tried 0-51 and 1-51

**Comment by Benman2785** [comment] 2016-11-21 14:03
ok - with strictness of 80% i wont have full encoder queue
but still fillerdata is bugged and still higher load on gpu and cpu

**Comment by Benman2785** [comment] 2016-11-21 14:05
wrong - with CBR still full encoder queue

**Comment by Xaymar** [comment] 2016-11-21 16:31
Your posted log shows nothing about a full encoder queue.

**Comment by Benman2785** [comment] 2016-11-21 18:20
but obs reports that and when u watch video you see stutter and lag

**Comment by Xaymar** [comment] 2016-11-21 19:22
OBS has no way to tell if the internal plugin queue is full, the only thing OBS reports is encoding overloaded. This can have multiple reasons:

- encode() didn't return in time or didn't return a frame within the acceptable time.
- rendering is stalling/lagging (visible as an FPS drop in the fps counter)
- the disk you record to is too slow

Any of these result in stutter (visible lag).

**Comment by Benman2785** [comment] 2016-11-22 10:05
mh - maybe it was my streamserver - my hoster had some problems last days -> i will try again when its fixed

**Comment by Benman2785** [comment] 2016-11-22 16:22
tested - has nothing to do with HDD -> also occured with local recording on SSD

**Comment by Xaymar** [comment] 2016-11-22 16:25
Again, there are no "queue full" messages in the log, so the issue is not in the settings or with the encoder. Until you can prove otherwise (log file will say so), I will consider this an invalid report.

**Comment by Benman2785** [comment] 2016-11-22 16:30
should i take a screenshot from obs when it happens?
and in the video you cleary see stutter

**Comment by Xaymar** [comment] 2016-11-22 16:32
No, I want a log file that actually says something is wrong. Follow the Troubleshooting Guide if you don't know how to produce one.

**Comment by Benman2785** [comment] 2016-11-22 21:43
i try my best to repoduce it in the log

**Comment by Xaymar** [comment] 2016-11-27 15:38
Any success actually reproducing this with it visible in the log? If not, then I will close this issue as invalid in two days.

**Comment by Benman2785** [comment] 2016-11-28 10:45
i cant let it show up in log - but it is still occuring

mostly any video i stream/record has it - and there is lots of stutter and lag

**Comment by Xaymar** [comment] 2016-11-28 15:30
If it still occurs I will need the following:

- New Raw Video File (not streamed, an actual recording by OBS)
- Log file with a fresh start of OBS and only that recording session (Please use the command line options '-verbose -log_unfiltered' for this)
- A screenshot of OBS at the moment it actually says "queue full"

Right now the only thing I actually can see is that for some reason OBS claims that more frames were skipped due to encoding lag, but the log file shows that all frames were encoded just fine.

**Comment by Benman2785** [comment] 2016-11-29 11:29
16.11.5 fixed that issue - maybe i had a bad install of 16.11.4

**Comment by Benman2785** [comment] 2016-11-30 15:32
error still persist with 16.11.5 & 1.4.3.0

http://benmanshafen.de/pics/OBS/Xaymar/Benman2785_Error.mp4
http://benmanshafen.de/pics/OBS/Xaymar/Benman2785_Error.jpg
http://benmanshafen.de/pics/OBS/Xaymar/Benman2785_Error.txt

![benman2785_error](https://cloud.githubusercontent.com/assets/21282980/20758546/7331c662-b71a-11e6-8b28-1e661651bb6b.jpg)
[Benman2785_Error.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/622165/Benman2785_Error.txt)

there you have it // ps it doesnt matter what settings i use -> everytime its the same...

**Comment by Xaymar** [comment] 2016-11-30 15:42
You are using View Mode Master and thus are disqualified from support.

**Comment by Benman2785** [comment] 2016-11-30 17:32
as i said it doesnt matter what settings i use - even if i use only twitch preset with everything on default it appears this way

**Comment by Benman2785** [comment] 2016-11-30 17:37
as shown here

[Benman2785_Error_2.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/622541/Benman2785_Error_2.txt)
http://benmanshafen.de/pics/OBS/Xaymar/Benman2785_Error_2.mp4

**Comment by Xaymar** [comment] 2016-11-30 18:11
Would you look at that, your last log file actually shows the dropping frame message!

`18:36:33.029: [AMF Encoder] GPU Encoder overloaded, dropping frame instead...`

Now with this, I've actually got a valid log file that isn't using highly experimental settings. So, let's take a look:

1. Time between SubmitInput highly varied, sometimes being as fast as 1ms and other times being as slow as 8ms.
2. Time between GetOutput also varied and I see some AMF_REPEAT entries there too.
3. OBS reports much more frames skipped than the plugin actually skipped.
4. VBV Buffer Size is at 565497 bits for some reason, the default for that is exactly the same as the target bitrate (not sure if obs glitched here).
5. OBS seems to have been running as 32-bit instead of 64-bit, this limits memory and thus the available space to store frames and packets. This also negatively affects performance on 64-bit systems as it limits the available instruction sets to smaller, slower ones.

From those issues, 2 are user errors (4, 5), one seems to be a bug in OBS (3) and two pretty much balanced each other out for the most part (1, 2). However there are strange entries that should not be there - AMF_REPEAT should never be returned unless B-Frames are being used.

Please fix 4 and 5 and then try again.

**Comment by Benman2785** [comment] 2016-11-30 18:19
i havent change VBV Buffer -> as i said i use your default preset

i will run it in 64 bit -> but have in mind some Webcams dont have 64bit drivers so they work shitty with 64bit OBS

**Comment by Benman2785** [comment] 2016-11-30 18:37
ok - when i manually set VBV Buffer to Bitrate and then switch back to auto it works fine -> so i think your plugin doesnt set VBV Buffersize correctly when switching to Default

when i set VBV Strictness to 0.00 it doesnt apear with my own custom setting (yet) -> maybe this needs some attenion from AMD

**Comment by Xaymar** [comment] 2016-12-01 08:07
> ok - when i manually set VBV Buffer to Bitrate and then switch back to auto it works fine -> so i think your plugin doesnt set VBV Buffersize correctly when switching to Default

I wonder what causes that, I've not yet found a reason for it happening.

**Closed as completed** 2016-12-02 10:00 UTC
Labels: status:solved, type:support
