### ISSUE TITLE
rc2 gets stuck after record >2min > stop > record > stop = stuck

### ISSUE THREAD

**Issue by wazerstar** [Xaymar/OBS-AMD-Advanced-Media-Framework#85] opened 2016-09-12 17:22 UTC
Was testing new RC2 release with simple mode & twitch preset

Hardware:
CPU: Intel 4790K
Graphics: AMD R9 290 4GB GDDR5 modded to 290x - Then remodded to 390x
**Driver 16.9.1 Hotfix**
Motherboard: Asus MAXIMUS VI FORMULA
Ram: 16GB DDR3 2400mhz
Disk: 1TB Samsung EVO 840

After termination the game, obs window finally made it stop.

**1.3.0pre8** Was not an issue 

[2016-09-12 07-02-05.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/467928/2016-09-12.07-02-05.txt)

**Comment by wazerstar** [comment] 2016-09-12 17:37
I see this and new post from MikhailAMD
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/19#issuecomment-246404117

**Comment by Xaymar** [comment] 2016-09-12 18:20
This could possibly be fixed in a future version, not entirely sure if it's even the same issue. Also if closing the game makes OBS respond again, the issue is not with the plugin.

Anyway, encoder getting stuck has already been reported here: #81

**Closed as completed by Xaymar** 2016-09-12 18:20 UTC
Labels: type:duplicate, status:solved
