### ISSUE TITLE
Microstuttering (I think?)

### ISSUE THREAD

**Issue by Compizfox** [Xaymar/OBS-AMD-Advanced-Media-Framework#204] opened 2017-03-04 22:25 UTC
Hi,

Here I am again. Since [my last issue](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/120) (also about stuttering) I upgraded from a HD7970 to a RX480. It's much better now, but not exactly perfect.

**Specs:**
Intel 2500k @ 4.6 GHz
Asus P8P67-M PRO
8 GB RAM @ 2133 MHz
RX480 8 GB

**Versions:**
OBS 18.0.0
AMF Encoder 1.4.3.10
AMD driver 17.2.1

I'm still trying to record smooth DiRT Rally footage which has proven quite difficult, unfortunately. The videos are much better than what I got with my HD7970; the really obvious stutters are gone. However, there is still some microstuttering which makes the video look significantly more 'choppy' than how the game looks in real time. The log (attached) does not indicate that there is any kind of encoding stalls involved.

I'm trying to record 1080p 60 fps video, on Preset "High Quality" and Quality Preset "Speed".

I have a sample video for you: https://host.tuxplace.nl/2017-03-04%2021-35-30.mp4 (It's the source video so it's quite big, sorry if it takes long to download)

I must note that AMD Relive does not produce much better results.

[2017-03-04 20-03-38.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/818948/2017-03-04.20-03-38.txt)

**Comment by Xaymar** [comment] 2017-03-04 22:45
I can't download your video, your hoster has awful speed and ping to Germany. Took over 5 minutes to even start the download, only to get stuck at 21 MB downloaded. Anyway, here are possible Solutions:

**Stuttering during Video Playback**: If it stutters during playback, you may need to remux the video using OBS or ffmpeg first. At the moment the timestamps OBS produces do not match the content timestamps, so players get confused.

**Stuttering during Recording/Streaming**: There are multiple solutions to this, any of these might help:

- Enable OpenCL Surface Transfer
- Set Keyframe Interval to 2-5 seconds instead of 1 (Keyframes require a lot of time to encode, cache clearing, etc)
- Set QP to 21/21 instead of 30/28
- Disable ReLive (it's constantly encoding if it's Enabled, no matter if Replay Buffer is actually active or not)
- Uninstall ReLive

There's a pre-release version that has the new Encoder features built-in, if you wish to test it (1.9.9.6).

**Comment by Compizfox** [comment] 2017-03-04 23:19
Thanks you for looking into this issue.

> I can't download your video, your hoster has awful speed and ping to Germany. Took over 5 minutes to even start the download, only to get stuck at 21 MB downloaded.

That's weird. I'm hosting from home but I'm in the Netherlands and I have 100 Mb/s fiber. I was uploading something else just ago so maybe you tried to download it at the same moment and my link was saturated. Anyway, I've also put it up on YouTube: https://www.youtube.com/watch?v=uSFozFif1Zg. A good part to look at is from 3:00, for example, where there is a panning shot.

Maybe I'm just picky, but other videos (of DiRT Rally) I watch at YouTube are just much... smoother, although it's 60 fps in both cases. I don't exactly know what it is.

> Stuttering during Video Playback: If it stutters during playback, you may need to remux the video using OBS or ffmpeg first. At the moment the timestamps OBS produces do not match the content timestamps, so players get confused.

Interesting. Does that cause stuttering? I don't think that's the problem in this case because remuxed/reencoded videos are still the same.

With "stuttering during recording" you are referring to stutters in the game instead of in the video? I don't have any stutters in-game while recording, just in the resulting video.

> Set QP to 21/21 instead of 30/28

I did try playing around with the QP values. I think I found that lower QPs (higher quality/bitrate) caused more stuttering, but I'm not 100% sure. I can verify this if needed.

> Disable ReLive (it's constantly encoding if it's Enabled, no matter if Replay Buffer is actually active or not)

Hmm, really? I did not know that. I only see any performance difference (in terms of framerate/frametimes) between switching Instant Replay on/off. I'll see if disabling it all together makes any difference.

I will try 1.9.9.6 and see if it's any better.

**Comment by Xaymar** [comment] 2017-03-04 23:40
> https://www.youtube.com/watch?v=uSFozFif1Zg

> With "stuttering during recording" you are referring to stutters in the game instead of in the video? I don't have any stutters in-game while recording, just in the resulting video.

I mean stuttering in the capture, with either Window or Game Capture. Game Capture often repeats frames, reducing the visible FPS but not the actual FPS it captured - this is what I found in my own recorded footage of Overwatch, Dirt Showdown and other games where my FPS varies a lot. I think you can disable this behaviour by setting "Limit Framerate" though I'm not sure. 

Also you should try OpenCL surface submission, as right now you are really pushing a lot of bandwidth straight up only through the CPU. You can find it if you set View Mode to Advanced or higher.

> Maybe I'm just picky, but other videos (of DiRT Rally) I watch at YouTube are just much... smoother, although it's 60 fps in both cases. I don't exactly know what it is.

There's Motion Blur, 60 fps, and a lot of other techniques that can be used to improve video quality (Optical Flow, Frame Blending if recording at 90, 120 or higher FPS, etc)

> I will try 1.9.9.6 and see if it's any better.

1.9.9.6 (the pre-release versions of 2.0.0.0) remove the threaded create/submit/query approach, massively reducing the encoder latency and the timestamps in the frames itself have also been improved to be accurate down to a nanosecond. It still doesn't help with the OBS timestamps though. :(

**Comment by Compizfox** [comment] 2017-03-05 15:20
> I mean stuttering in the capture, with either Window or Game Capture. Game Capture often repeats frames, reducing the visible FPS but not the actual FPS it captured - this is what I found in my own recorded footage of Overwatch, Dirt Showdown and other games where my FPS varies a lot. I think you can disable this behaviour by setting "Limit Framerate" though I'm not sure.

I see. It sounds plausible; the footage is in 60 fps but it does not look like 60 fps. So this hypothesis where frames are getting duplicated sounds logical.

I am actually playing at > 100 fps (I have a 144 Hz monitor with FreeSync). In OBS under "Video" I have the framerate set to 60 fps, so it should capture at 60 fps. Is this the "Limit framerate" setting you are referring to or do you mean something else?

Would playing in 60 fps (V-synced) result in smoother videos? The big drawback of this is that I lose FreeSync and the high refreshrate in-game of course, but I can try if that makes a difference.

> Also you should try OpenCL surface submission, as right now you are really pushing a lot of bandwidth straight up only through the CPU. You can find it if you set View Mode to Advanced or higher.

I tried setting OpenCL to "Enabled" but the setting does not stick. It reverts to "Disabled" every time. This is with 1.9.9.6.

> There's Motion Blur, 60 fps, and a lot of other techniques that can be used to improve video quality (Optical Flow, Frame Blending if recording at 90, 120 or higher FPS, etc)

I'd love to record at 120 fps but it looks like that's not feasible with my card. I get massive encoder stalls when I try that.

**Comment by Xaymar** [comment] 2017-03-05 21:55
Thanks to GitHubs new Terms of Services, this Issue is now available over on GitLab. Sign in using Twitter, GitHub or BitBucket, or sign up with a new Account.

https://gitlab.digitaldawnstudios.com/Xaymar/obs-studio_amf-encoder-plugin/issues/204

**Comment by Xaymar** [comment] 2017-03-06 01:03
GitHub seems to have removed most offending statements from the ToS now, reopening.

**Comment by Xaymar** [comment] 2017-03-08 21:03
> Would playing in 60 fps (V-synced) result in smoother videos? The big drawback of this is that I lose FreeSync and the high refreshrate in-game of course, but I can try if that makes a difference.

It would help reduce the game capture load.

> I tried setting OpenCL to "Enabled" but the setting does not stick. It reverts to "Disabled" every time. This is with 1.9.9.6.

I have heard of this happening, not sure what causes it yet.

> I'd love to record at 120 fps but it looks like that's not feasible with my card. I get massive encoder stalls when I try that.

Encoder stalling usually means that the GPU encoder is at it's limit. The RX 480 is capable of 120 fps and more with Speed preset in CBR, not sure about CQP.

**Comment by R33D3M33R** [comment] 2017-03-12 21:03
Hello,

I have been having the choppy video problem for a long time now. I tried different software: OBS, MSI Afterburner, ReLive and tweaked it, but nothing seems to help. For me it looks like a issue on AMDs part (a bottleneck) which they will have to fix. When they had OpenEncode (pre 15.7) I could record fluid 720p60 videos, now with AMF it's mission impossible.

I would suggest that you report this via the AMD Issue Reporting Form so they could have a look into it. The more people report this, the more chance we will have for this to get fixed fast.

**Comment by Compizfox** [comment] 2017-03-16 21:29
> It would help reduce the game capture load.

I tried playing at 60 fps (V-synced) but I don't think it made any difference.

> Encoder stalling usually means that the GPU encoder is at it's limit. The RX 480 is capable of 120 fps and more with Speed preset in CBR, not sure about CQP.

Well, it seems mine definitely is not:

	22:21:10.495: ==== Recording Start ===============================================
	22:21:10.495: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Video/2017-03-16 22-21-10.mkv'...
	22:21:58.370: [ffmpeg muxer: 'adv_file_output'] Output of file 'C:/Video/2017-03-16 22-21-10.mkv' stopped
	22:21:58.370: Output 'adv_file_output': stopping
	22:21:58.370: Output 'adv_file_output': Total encoded frames: 5490
	22:21:58.370: Output 'adv_file_output': Total drawn frames: 5745
	22:21:58.370: Output 'adv_file_output': Number of skipped frames due to encoding lag: 4994 (91.0%)
	22:21:58.370: Output 'adv_file_output': Number of lagged frames due to rendering lag/stalls: 1912 (33.3%)
	22:21:58.370: ==== Recording Stop ================================================

This is 120 fps recording with CBR, speed, 20 Mb/s, in DiRT Rally.

**Comment by Xaymar** [comment] 2017-03-16 21:53
Is your card overclocked? If it is (either by you or the vendor) you must return it back to original (reference) clock speeds. There is a significant encoding overhead if the GPU is overclocked to a speed where it doesn't work like it should.

**Comment by Compizfox** [comment] 2017-03-16 22:47
It is. I'll test with reference clocks. It sounds really counter-intuitive though.

**Comment by Xaymar** [comment] 2017-03-16 23:05
There's a tool on [the wiki](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-Support) that can help you figure out the encode speed you get with certain overclocks. I used this to push my RX 480 a little bit higher to get 60 fps on AVC 1080p Quality instead of 56.

**Comment by Compizfox** [comment] 2017-03-16 23:43
Weird, the speed test gives this results (all 1080p):

Speed:

	 Average (Max, fr#) Encode Latency: 7.2 ms (16.1 ms frame# 0)
	 Average (Max) Frame size: 3010 bytes (7688 bytes)
	 Frames processed: 300 Frame process time: 7.2ms FPS: 138.6
	 Average FPS: 138.6 Combined FPS: 138.6

Balanced:

	 Average (Max, fr#) Encode Latency: 9.7 ms (35.6 ms frame# 0)
	 Average (Max) Frame size: 2448 bytes (7688 bytes)
	 Frames processed: 300 Frame process time: 9.7ms FPS: 103.3
	 Average FPS: 103.3 Combined FPS: 103.3

Quality:

	 Average (Max, fr#) Encode Latency: 17.5 ms (21.1 ms frame# 205)
	 Average (Max) Frame size: 2368 bytes (7688 bytes)
	 Frames processed: 300 Frame process time: 17.6ms FPS: 56.9
	 Average FPS: 56.9 Combined FPS: 56.9

This is with my overclock, however I do not think the test is reliable in that regard because it does not stress the GPU and my GPU did not hit boost clock while the test was running.

**Comment by Xaymar** [comment] 2017-03-16 23:49
That means that the bottleneck happens not because of the encoder, but because of the PCI-E bus not being capable of sending the individual frames fast enough. You should enable OpenCL like I mentioned [here](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/204#issuecomment-284190282) and also try and see if the 1.9.9.6 preview gives better results.

**Comment by Compizfox** [comment] 2017-03-16 23:51
I can't enable OpenCL; the setting does not stick and resets to Disabled when I close and re-open the settings.

This is with v1.9.9.6 ;)

My motherboard only has PCI-e 2.0. Could that be a problem?

**Comment by Xaymar** [comment] 2017-03-17 01:07
Oh right, I have not released a fix for that publicly yet.

**Comment by Xaymar** [comment] 2017-03-18 23:53
> I can't enable OpenCL; the setting does not stick and resets to Disabled when I close and re-open the settings.

After thorough testing, there is nothing on the plugins side doing this. Start with a clean obs install and a clean profile, as I otherwise have no clue what's causing that.

**Comment by Compizfox** [comment] 2017-03-19 15:21
I completely removed OBS Studio (wiping user settings too), then re-installed it and the AMF plugin v1.9.9.6 but the issue persists.

I also tried deleting `%appdata%\obs-studio`.

Anything I can do on my side to debug this?

I do see the error `rtmp-common.c: [initialize_output] Could not find service ''` in the log after saving the settings, not sure if it's related.

**Comment by Xaymar** [comment] 2017-03-19 15:23
I'll need a copy of your complete obs-studio settings then, since it is completely unreproducable on my end. Send it to info@xaymar.com and I'll try to figure out what causes this.

Edit: The complete settings means an archive of the %APPDATA%/obs-studio directory

**Comment by Xaymar** [comment] 2017-03-19 15:38
Thanks for sending me that, I've taken a look at the settings themselves:

- OpenCL is set to Enabled in both the .json and .json.bak file (so it's clearly being saved)
- There is an extra property (AMF.H264.VBVBuffer.Strictness) which should not exist anymore.
- View Mode is only set to 1 (Advanced)

OpenCL requires that View Mode is set to 2 (Expert) and not 1 (Advanced).

**Comment by Compizfox** [comment] 2017-03-19 15:42
Thanks for looking into it!

Weird, it shows the OpenCL property here in View Mode "Advanced". If OpenCL requires that it is set to Expert, then shouldn't Advanced hide that property?

I can confirm that it shows the value of the OpenCL setting correctly when in View Mode "Expert". (I only just now tested that)

I'll try to record in 120 fps now to see if it works.

**Comment by Xaymar** [comment] 2017-03-19 15:43
> Weird, it shows the OpenCL property here in view mode "Advanced". If OpenCL requires that it is set to Expert, then shouldn't Advanced hide that property?

Indeed it should, I don't know why it doesn't for you. I'll take a look into the plugin code for anything that could cause that.

**Comment by Compizfox** [comment] 2017-03-19 16:55
Still not a chance of recording 120 fps video even with OpenCL enabled.

	17:53:57.525: ==== Recording Start ===============================================
	17:53:57.525: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Users/Lars Veldscholte/Videos/2017-03-19 17-53-57.mkv'...
	17:54:20.259: [ffmpeg muxer: 'adv_file_output'] Output of file 'C:/Users/Lars Veldscholte/Videos/2017-03-19 17-53-57.mkv' stopped
	17:54:20.259: Output 'adv_file_output': stopping
	17:54:20.259: Output 'adv_file_output': Total encoded frames: 2302
	17:54:20.259: Output 'adv_file_output': Total drawn frames: 2728
	17:54:20.259: Output 'adv_file_output': Number of skipped frames due to encoding lag: 2573 (111.8%)
	17:54:20.259: Output 'adv_file_output': Number of lagged frames due to rendering lag/stalls: 121 (4.4%)
	17:54:20.259: ==== Recording Stop ================================================

I tried **disabling** OpenCL and this works a lot better!

	17:55:53.427: ==== Recording Start ===============================================
	17:55:53.427: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Users/Lars Veldscholte/Videos/2017-03-19 17-55-52.mkv'...
	17:56:16.900: [AMF] <Id: 24> Submitting Surface failed , error AMF_INPUT_FULL (code 25)
	17:56:17.006: [AMF] <Id: 24> Submitting Surface failed , error AMF_INPUT_FULL (code 25)
	17:56:18.157: [ffmpeg muxer: 'adv_file_output'] Output of file 'C:/Users/Lars Veldscholte/Videos/2017-03-19 17-55-52.mkv' stopped
	17:56:18.157: Output 'adv_file_output': stopping
	17:56:18.157: Output 'adv_file_output': Total encoded frames: 2963
	17:56:18.157: Output 'adv_file_output': Total drawn frames: 2968
	17:56:18.157: Output 'adv_file_output': Number of skipped frames due to encoding lag: 55 (1.9%)
	17:56:18.157: Output 'adv_file_output': Number of lagged frames due to rendering lag/stalls: 537 (18.1%)
	17:56:18.157: ==== Recording Stop ================================================

**Comment by Xaymar** [comment] 2017-03-19 17:21
So your card performs worse with OpenCL? Interesting.

**Comment by Compizfox** [comment] 2017-03-19 17:27
Well I do get a lot of `[AMF] <Id: 24> Submitting Surface failed , error AMF_INPUT_FULL (code 25)` with OpenCL disabled. I guess that means that the PCI-e bus is saturated? It results in stutters, too.

In either case (OpenCL disabled or enabled) I cannot record in 120 fps without stuttering.

**Comment by Xaymar** [comment] 2017-03-19 17:31
Yeah, then the PCI-E bus is saturated.

**Comment by Compizfox** [comment] 2017-03-19 17:32
I guess the often-cited claim that PCI-e 2.0 does not have any performance decrease compared to 3.0 is not true in all cases then...

**Comment by Xaymar** [comment] 2017-03-19 17:44
PCI-E 2.0 x16 is basically PCI-E 3.0 x4/x8, minus a few other differences. So yeah, you're not getting that 120fps on 2.0. It requires at least 3981312000 bits/sec (3.9gbit/s) to handle that on NV12 format.

Edit: Wikipedia states this:

> Like 1.x, PCIe 2.0 uses an 8b/10b encoding scheme, therefore delivering, per-lane, an effective 4 Gbit/s max transfer rate from its 5 GT/s raw data rate.

**Comment by Xaymar** [comment] 2017-03-20 20:26
OpenCL field has been fixed by #214 (implemented by 1.9.9.7)

**Closed as completed** 2017-04-05 07:57 UTC
Labels: status:solved, type:support

**Comment by Compizfox** [comment] 2017-05-05 14:07
> So your card performs worse with OpenCL? Interesting.

Not sure if this info is of any use to you, but some testing with 2.0.0 revealed that it is OpenCL *transfer* specifically that results into worse performance (encoder lag) for me. OpenCL *conversion* works fine.

**Comment by Xaymar** [comment] 2017-05-07 05:41
Just to be sure, keep both off. OpenCL conversion is more of a compatibility option than anything else and just adds another layer of dependency on top of AMF.
