### ISSUE TITLE
Unexplainable OpenCL crash with certain Hardware/System

### ISSUE THREAD

**Issue by aquamacho** [Xaymar/OBS-AMD-Advanced-Media-Framework#209] opened 2017-03-15 12:14 UTC
Hi xaymar and super big thx for your hard work with this awesome plugin.
Im trying to stream GTA 5 (i think game does not matter here) to youtube, all goes good but at around hour and 30 stream cuts off, OBS does not indicate anything exept where bitrate couter located shows 0 kbps. When pressing "stop stream" button nothing happens, only exiting OBS stops stream completely.

system specs:
Windows 8.1 x64
AMD Phenom II X6 1045T @3.3
MSI R7770 Power Edition 1GD5/OC (gcn 1.0) hooked up to main monitor
9600 GT Asus Magic HDMI second monitor.
8G ddr3 ram
asrock 970 extreme3 mobo.
Plugin ver - 1.9.9.6 (pre-release)
Drivers 17.3.1 (ReLive is not installed).

Obs stuff:
Resolution - 1920x1080
Preset - YouTube with Pre-Pass mode enabled (full Size)
Quality - Balanced
Bitrate - 20k (20000)
Changed VBV Buffer size from auto to 50000 because bitrate sometimes spikes to 27k.
Fps - 60

This issue happens only with 1.9.9.6 plugin version.
[2017-03-15 09-52-20.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/844375/2017-03-15.09-52-20.txt)
3. I wanted to ask how much strain puts OBS preview on gpu when im recording or streaming.
Thx.
P.S. Dunno why, but im scared for some reason when im asking for help, i feel like im gonna get bark at for being dumb (what is probably true) or smth.

**Comment by Xaymar** [comment] 2017-03-15 13:26
Hey, thanks for trying out the Preview version. First I'd like to correct something in your configuration:

> Changed VBV Buffer size from auto to 50000 because bitrate sometimes spikes to 27k.

You just made the VBV Buffer bigger than Automatic with 50% does. Your spikes will be even larger now (up to 50mbit instead of just up to 20mbit per GOP). Aside from that I don't see what caused the error itself, though you do have View Mode set to Master which normally excludes you from support.

Your actual issue comes from OpenCL failing to convert the frame into a GPU readable format. The reason for this is not clearly visible since OBS was not running in debug mode:

``` 
11:24:54.472: [AMF] <Id: 16> [Conversion Pass] Conversion of Surface to OpenCL failed, error AMF_FAIL (code 1)
``` 

So in order to figure out why and what happened, I will need you to start OBS Studio with the following command line (just edit the shortcut to have this at the end):

```
--verbose --unfiltered_log
```

The log file will be several megabytes, but it will show exactly what went wrong and why, so that I can work on solving this. I recommend compressing it first before uploading using winrar or 7-zip.

**Comment by aquamacho** [comment] 2017-03-15 14:43
So i just unplugged my second gpu (9600gt) to be able to stream\record with OpenCL properly working after i read a bit of FAQ whitch im not in the first place (im retarded).
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-opencl-does-not-work
I will stream now with debug mode on and will upload log if this gonna happen again, if its not im gonna upload anyways.
P.S. and adjust vbv buffer back to auto? or i can make 20 mbit?
I mean if im using YT preset, buffer will be 3500 by the preset default ?

**Comment by Xaymar** [comment] 2017-03-15 14:52
> So i just unplugged my second gpu (9600gt) to be able to stream\record with OpenCL properly working after i read a bit of FAQ whitch im not in the first place (im retarded).
> https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-opencl-does-not-work
> I will stream now with debug mode on and will upload log if this gonna happen again, if its not im gonna upload anyways.

I'll be waiting, I'm sure that if this is an AMD OpenCL bug they will want to fix it.

> P.S. and adjust vbv buffer back to auto? or i can make 20 mbit?
> I mean if im using YT preset, buffer will be 3500 by the preset default ?

Yes, the Buffer should be identical to the bitrate. If VBV Buffer is set to Automatic, 50% means same as bitrate, 0% means maximum possible (**not recommended at all**) and anything above 50% restricts it further until 100% means as strict as possible.

**Comment by aquamacho** [comment] 2017-03-15 16:50
I think this was my second GPU that was causing the problem, im currently at almost 2 hours in stream and no problems so far.
Im happy that this is not caused by plugin. I will post the log later.

**Comment by aquamacho** [comment] 2017-03-15 17:49
so here the log without a crash (Github wont let me upload .zip to the site for some reason)
https://drive.google.com/open?id=0B8uCAZ74gXrRUklQY01ZRDdQRjQ
i will now go for it and test with both GPU`s in place.

cant even launch obs anymore :P
[Crash 2017-03-15 20-12-26.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/845594/Crash.2017-03-15.20-12-26.txt)

Local recording with both GPU`s, OpenCL enabled, but "Encoder Overloaded" massage was all the time.
[2017-03-15 20-40-45.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/845655/2017-03-15.20-40-45.txt)
Now will do Stream for 1 hour again. Brb.

**Comment by Xaymar** [comment] 2017-03-15 19:51
> 2017-03-15 20-40-45.txt

The encoder didn't even encode anything, it literally just sat there doing nothing. Weird.

**Comment by aquamacho** [comment] 2017-03-15 21:01
As promised. Crashed (not exactly crashed, but stopped sending data to YT) after 1 hour 40 minutes.
https://drive.google.com/open?id=0B8uCAZ74gXrRdE12T3RuemwzbnM

> 2017-03-15 20-40-45.txt

This was 1 minute recording, just to test OpenCL.
I think i will unplug 9600gt from my PC from now on.
Thx for help and again, sorry for wasting your time <3

**Comment by Xaymar** [comment] 2017-03-15 21:08
```
22:48:10.791: [AMF Runtime] [22:48:10.757][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.791: [AMF Runtime] [22:48:10.763][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.791: [AMF Runtime] [22:48:10.775][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.791: [AMF Runtime] [22:48:10.788][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.815: [AMF] SubmitInput: frame->pts(  327664) TS( 196598400000000) Duration(      -600000000)
22:48:10.815: [AMF] QueryOutput: frame->dts(  327650) TS( 196590000000000) Duration(      -600000000) frame->pts(  327650) Size(           41673)
22:48:10.842: [AMF] SubmitInput: frame->pts(  327665) TS( 196599000000000) Duration(      -600000000)
22:48:10.842: [AMF] QueryOutput: frame->dts(  327651) TS( 196590600000000) Duration(      -600000000) frame->pts(  327651) Size(           41672)
22:48:10.870: [AMF] SubmitInput: frame->pts(  327666) TS( 196599600000000) Duration(      -600000000)
22:48:10.870: [AMF] QueryOutput: frame->dts(  327652) TS( 196591200000000) Duration(      -600000000) frame->pts(  327652) Size(           41673)
22:48:10.891: [AMF Runtime] [22:48:10.798][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.891: [AMF Runtime] [22:48:10.814][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.891: [AMF Runtime] [22:48:10.824][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.891: [AMF Runtime] [22:48:10.842][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.891: [AMF Runtime] [22:48:10.849][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.891: [AMF Runtime] [22:48:10.869][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.891: [AMF Runtime] [22:48:10.883][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.898: [AMF] SubmitInput: frame->pts(  327667) TS( 196600200000000) Duration(      -600000000)
22:48:10.898: [AMF] QueryOutput: frame->dts(  327653) TS( 196591800000000) Duration(      -600000000) frame->pts(  327653) Size(           41673)
22:48:10.920: [AMF] SubmitInput: frame->pts(  327668) TS( 196600800000000) Duration(      -600000000)
22:48:10.920: [AMF] QueryOutput: frame->dts(  327654) TS( 196592400000000) Duration(      -600000000) frame->pts(  327654) Size(           41672)
22:48:10.947: [AMF] SubmitInput: frame->pts(  327669) TS( 196601400000000) Duration(      -600000000)
22:48:10.948: [AMF] QueryOutput: frame->dts(  327655) TS( 196593000000000) Duration(      -600000000) frame->pts(  327655) Size(           41673)
22:48:10.972: [AMF] SubmitInput: frame->pts(  327670) TS( 196602000000000) Duration(      -600000000)
22:48:10.973: [AMF] QueryOutput: frame->dts(  327656) TS( 196593600000000) Duration(      -600000000) frame->pts(  327656) Size(           41673)
22:48:10.988: [AMF] SubmitInput: frame->pts(  327671) TS( 196602600000000) Duration(      -600000000)
22:48:10.988: [AMF] QueryOutput: frame->dts(  327657) TS( 196594200000000) Duration(      -600000000) frame->pts(  327657) Size(           41672)
22:48:10.991: [AMF Runtime] [22:48:10.897][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.991: [AMF Runtime] [22:48:10.905][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.991: [AMF Runtime] [22:48:10.919][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.991: [AMF Runtime] [22:48:10.926][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.991: [AMF Runtime] [22:48:10.947][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.991: [AMF Runtime] [22:48:10.954][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.991: [AMF Runtime] [22:48:10.972][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.991: [AMF Runtime] [22:48:10.978][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:10.991: [AMF Runtime] [22:48:10.988][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.003: [AMF] SubmitInput: frame->pts(  327672) TS( 196603200000000) Duration(      -600000000)
22:48:11.004: [AMF] QueryOutput: frame->dts(  327658) TS( 196594800000000) Duration(      -600000000) frame->pts(  327658) Size(           41673)
22:48:11.030: [AMF] SubmitInput: frame->pts(  327673) TS( 196603800000000) Duration(      -600000000)
22:48:11.030: [AMF] QueryOutput: frame->dts(  327659) TS( 196595400000000) Duration(      -600000000) frame->pts(  327659) Size(           41673)
22:48:11.056: [AMF] SubmitInput: frame->pts(  327674) TS( 196604400000000) Duration(      -600000000)
22:48:11.056: [AMF] QueryOutput: frame->dts(  327660) TS( 196596000000000) Duration(      -600000000) frame->pts(  327660) Size(           41672)
22:48:11.082: [AMF] SubmitInput: frame->pts(  327675) TS( 196605000000000) Duration(      -600000000)
22:48:11.082: [AMF] QueryOutput: frame->dts(  327661) TS( 196596600000000) Duration(      -600000000) frame->pts(  327661) Size(           41673)
22:48:11.091: [AMF Runtime] [22:48:10.993][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.091: [AMF Runtime] [22:48:11.003][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.091: [AMF Runtime] [22:48:11.008][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.091: [AMF Runtime] [22:48:11.030][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.091: [AMF Runtime] [22:48:11.037][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.091: [AMF Runtime] [22:48:11.056][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.091: [AMF Runtime] [22:48:11.069][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.091: [AMF Runtime] [22:48:11.082][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.091: [AMF Runtime] [22:48:11.088][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.110: [AMF] SubmitInput: frame->pts(  327676) TS( 196605600000000) Duration(      -600000000)
22:48:11.110: [AMF] QueryOutput: frame->dts(  327662) TS( 196597200000000) Duration(      -600000000) frame->pts(  327662) Size(           41673)
22:48:11.133: [AMF] SubmitInput: frame->pts(  327677) TS( 196606200000000) Duration(      -600000000)
22:48:11.133: [AMF] QueryOutput: frame->dts(  327663) TS( 196597800000000) Duration(      -600000000) frame->pts(  327663) Size(           41672)
22:48:11.153: [AMF] <Id: 15> [Conversion Pass] Conversion of Surface to OpenCL failed, error AMF_FAIL (code 1)
22:48:11.153: [AMF] <Plugin::Interface::H264Interface::~H264Interface> Finalizing...
22:48:11.191: [AMF Runtime] [22:48:11.109][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.191: [AMF Runtime] [22:48:11.114][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(68):OpenCL failed, error = -4:clEnqueueAcquireD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.191: [AMF Runtime] [22:48:11.133][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(78):OpenCL failed, error = -4:clEnqueueReleaseD3D11ObjectsKHR(m_clCommandQueue, 1, &clImage, 0, NULL, &clWaitEvent)
22:48:11.191: [AMF Runtime] [22:48:11.138][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(174):OpenCL failed, error = -1007:InteropFromDX11ToOpenCLImage() clCreateFromD3D11Texture2DKHR() failed
22:48:11.191: [AMF Runtime] [22:48:11.153][AMFSurfaceImpl]    Error: ..\..\..\..\..\runtime\src\core\SurfaceImpl.cpp(240):Assertion failed:Convert() - InteropSurface failed
22:48:11.291: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.291: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.291: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.291: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.291: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.291: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
22:48:11.292: [AMF Runtime] [22:48:11.243][AMFDeviceDX11Impl]  Warning: Possible memory leak detected: DX11 device is being destroyed, but has 2 surfaces associated with it. This is OK if there are references to the device outside AMF.
```

Looks like you've found a bug with AMDs OpenCL color conversion! I'll be reporting this to AMD in hopes that it gets fixed.

**Comment by aquamacho** [comment] 2017-03-15 21:12
Are you sure this is related to AMD and not Nvidia? or both? Mb they conflicting with each other.
This is only happening when im using both GPU`s.

**Comment by Xaymar** [comment] 2017-03-15 21:14
They should not be conflicting, as I explicitly specify which device the encoder should be using for OpenCL. AMD will be able to tell me more about the cause and hopefully work together with other vendors on fixing this too if that is the case.

**Comment by aquamacho** [comment] 2017-03-15 21:36
actually, i has a bigger issue than this, that mind boggling me, every second if bitrate is set to lets say 3500, image Re-renders ? i dont know how to discribe it, i think this is related to IDR period.
This issue was described here:
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/25
What can i do about it?

**Comment by Xaymar** [comment] 2017-03-15 21:45
25 is not related to the issue you are describing. Anyway, most of the I-Frame flicker goes away if Minimum QP is set to 18 and stays there. Some of it can also be reduced by making the VBV Buffer stricter (smaller), but normally the only time you should ever see I-Frame flickering is when switching immediately from very high motion footage to a perfect still frame - and then it usually lasts ~1-2 seconds.

**Comment by aquamacho** [comment] 2017-03-15 21:48
here`s example:
https://drive.google.com/open?id=0B8uCAZ74gXrRVlpmdWdRWGJZZlE

**Comment by Xaymar** [comment] 2017-03-15 21:51
Add a Media Source and play back this file in it: http://cdn.xaymar.com/enc-amf/UnigineValleySample.mp4, record that and then upload a sample of that. That way we both have the same source footage to work off of.
Edit: I recommend downloading the video first, it's 1.6gb big.

**Comment by aquamacho** [comment] 2017-03-15 21:55
Working on it...
Where can i upload so its will be quicker for you to access to?

**Comment by Xaymar** [comment] 2017-03-15 21:56
Same as before.

**Comment by aquamacho** [comment] 2017-03-15 22:04
https://drive.google.com/open?id=0B8uCAZ74gXrRT3FCRmpTdGc0Q1E
This is with Pre-pass enabled, its gonna be worse without it, i think.
Pre-pass Disabled, VBV Strictness 100% \ 3500 bitrate \ YT profile 18 min QP
I personally do not touch any settings if im not certain what they mean, so its always default, except OpenCL.
https://drive.google.com/open?id=0B8uCAZ74gXrRTGE1QzlVeTI4TGs

**Comment by MSxDOS** [comment] 2017-03-15 22:09
aquamacho, 17.3.2 just got released.

**Comment by aquamacho** [comment] 2017-03-15 22:24
> aquamacho, 17.3.2 just got released.

Newer drivers dont matter for me as gcn 1.0 owner, except when Xaymar adds new feature to the plugin :P
But im gonna update anyways :D

**Comment by Xaymar** [comment] 2017-03-15 22:33
> Newer drivers dont matter for me as gcn 1.0 owner, exept when Xaymar adds new feature to the plugin :P

Check the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting#2-do-you-have-the-latest-updates-installed) for what it says about not running the latest version.

**Comment by aquamacho** [comment] 2017-03-15 22:33
> But im gonna update anyways

Back to Flickering issue, i was testing OBS from  2014~ - 2016 https://obsproject.com/forum/threads/obs-branch-with-amd-vce-support.13996/ with 14.4 drivers and still has same issue... nothing helps except adding 20000 bitrate.
I think this is why VCE 2.0 was released.

I was wondering, is there a way to mix h.264 software with VCE to work together, and get performance of VCE with Quality of software. :imagination:

**Comment by Xaymar** [comment] 2017-03-15 23:27
> Back to Flickering issue, i was testing OBS from 2014~ - 2016 https://obsproject.com/forum/threads/obs-branch-with-amd-vce-support.13996/ with 14.4 drivers and still has same issue... nothing helps except adding 20000 bitrate.
> I think this is why VCE 2.0 was released.

VCE2 also had some issues, VCE3 solved more of them and VCE3.1 (GCN4) is a disappointing step back from VCE3 (Tonga Tonga XT) :/

> I was wondering, is there a way to mix h.264 software with VCE to work together, and get performance of VCE with Quality of software. :imagination:

No. The Hardware is locked down by AMD, and there is not much you can do.

**Comment by aquamacho** [comment] 2017-03-24 04:00
Hmmm, was streaming yesterday and this happened again, Crash after 1 hour 31~. I was tinkering with OpenCL on and off, because i was getting encoder overloaded messages. All seems good exept this time OpenCL crashed while being turned off?
Strangely enough, while OpenCL is on, im not getting any OpenCL crashes. Weird.

> 19:46:24.922: [AMF]   OpenCL: Disabled

> 21:17:26.776: [AMF Runtime] [21:17:26.723][DeviceComputeImplDX11]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplDX11.cpp(174):OpenCL failed, error = -1007:InteropFromDX11ToOpenCLImage() clCreateFromD3D11Texture2DKHR() failed

Also my second Gpu was unplugged and nvidia drivers was uninstalled i think.

Log here.
https://drive.google.com/open?id=0B8uCAZ74gXrRcWVCZkhuYWtoOFk

p.s. this was with amd`s latest non-WHQL drivers 17.3.3, i will roll back to 17.3.1.

Hmm, also, i wanned to ask about I-Frame flicker, can this be sort of "resolved" by setting IDR period to something like 1000 frames?

**Comment by Xaymar** [comment] 2017-03-24 19:02
Next version will have a separate OpenCL switch for conversion (#212).

> Hmm, also, i wanned to ask about I-Frame flicker, can this be sort of "resolved" by setting IDR period to something like 1000 frames?

IDR Period is the period between IDR frames. If you set it higher, that also means that anyone wanting to view your stream has to wait a longer time.

**Comment by Benman2785** [comment] 2017-04-12 13:13
Xaymar - usually that should be fixed with KeyFrameIntervall -> 2s and then you should see the video // i think your IDR overwrites the keyframe value -> every Keyframe is an i-frame, and every idr frame is a i frame, but not every i frame is an idr-frame (and i think there is the problem with your plugin)

**Comment by Xaymar** [comment] 2017-04-13 10:03
> Xaymar - usually that should be fixed with KeyFrameIntervall -> 2s and then you should see the video // i think your IDR overwrites the keyframe value -> every Keyframe is an i-frame, and every idr frame is a i frame, but not every i frame is an idr-frame (and i think there is the problem with your plugin)

Again, Keyframe Interval and IDR Period are identical. See #220 for what you actually want to do.

**Comment by Benman2785** [comment] 2017-04-13 10:41
yeah - i checked again this night and u r right - IDR Period is Keyframe-Intervall ;)

what we need is #220 ;)

otherwise 1.9.9.11 OpenCL (transfer and conversion) works super good

**Comment by Xaymar** [comment] 2017-05-14 18:18
I'm considering this solved as you can now completely turn off OpenCL and use DirectCompute and Host transfer instead.

**Closed as completed by Xaymar** 2017-05-14 18:18 UTC
Labels: type:bug, status:solved
