### ISSUE TITLE
[2.1.2] Immediately Crashes On Encoder Start

### ISSUE THREAD

**Issue by Xbye** [Xaymar/OBS-AMD-Advanced-Media-Framework#240] opened 2017-05-13 22:46 UTC
Old 2.0.0.0 currently works. I reset my configuration upon upgrading to 2.1.2 . Switching between Full and Partial didn't change anything.

**RX 480** - _17.5.1_

**OBS Log**: https://gist.github.com/anonymous/b3ad82d2b13f650c59703b34a0d8680f
**Crash Log**: https://pastebin.com/Ngk5qUBz

**Comment by Xaymar** [comment] 2017-05-13 23:07
32-Bit, already known and reported. This is a driver bug.

**Comment by Xaymar** [comment] 2017-05-15 01:04
A temporary solution is to not use 32-bit and instead use 64-bit until AMD releases a driver with this fixed.

**Comment by Xbye** [comment] 2017-05-15 14:04
>A temporary solution is to not use 32-bit and instead use 64-bit until AMD releases a driver with this fixed.

This isn't a solution for me since I still haven't been able to fix the floaty mouse issue that comes with 64-bit. I should be fine for now since 2.0.0.0 still works.

**Comment by Nuc1eoN** [comment] 2017-05-15 16:44
So the 64bit version of OBS is still buggy? Thought it does well on 64bit systems.

**Comment by Xaymar** [comment] 2017-05-15 16:50
> This isn't a solution for me since I still haven't been able to fix the floaty mouse issue that comes with 64-bit. I should be fine for now since 2.0.0.0 still works.

Sucks for you. Since so far I've seen nobody else reproduce that problem, I don't think it's something anyone can ever solve.

**Comment by Nuc1eoN** [comment] 2017-05-15 17:40
So the bug is in the 64bit Radeon driver?

**Comment by Xaymar** [comment] 2017-05-15 17:43
@Nuc1eoN I keep seeing emails pop up from you with no related comment. To answer the question, the bug **is in the 32-bit driver** not in the 64-bit one.

**Comment by Xaymar** [comment] 2017-05-21 16:17
2.1.5 contains a workaround for the time being.

**Comment by Xaymar** [comment] 2017-07-27 17:51
Driver 17.7.2 supposedly fixes this, have not confirmed yet.

**Comment by Xaymar** [comment] 2017-07-30 19:32
Fixed by 17.7.2

**Closed as completed by Xaymar** 2017-07-30 19:32 UTC
Labels: type:bug, status:solved
