### ISSUE TITLE
VBAQ creates stutter in output (and impacts game)

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#309] opened 2018-03-19 22:21 UTC
Windows 10 Creators x64
AMD FX-9590 @stock+UV
RX 580 4G (Nitro+ OC)
GigaByte 990FX-Gaming
16G DDR3 @1670mhz CL9-9-9-27 (4x4G - and my MemoryController sucks)

OBS 21.1.0
Plugin ver - 2.3.3
Drivers 18.3.2

settings:
![720p48_h264 4872kbps_aac 128kbps](https://user-images.githubusercontent.com/21282980/37625301-ae4c6c8a-2bcb-11e8-999b-acaa6a972d20.jpg)

VBAQ: http://benmanshafen.de/obs/xaymar/2.3.3/720p48_h264+4872kbps_aac+128kbps_noHRD_CABAC_VBAQ_tra_b2_que3.flv
![720p48_h264 4872kbps_aac 128kbps_nohrd_cabac_vbaq_tra_b2_que3](https://user-images.githubusercontent.com/21282980/37625340-cf86e394-2bcb-11e8-881c-44180b1c9115.jpg)

without:
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_h264+4872kbps_aac+128kbps_noHRD_CABAC_tra_b2_que3.flv
![720p48_h264 4872kbps_aac 128kbps_nohrd_cabac_tra_b2_que3](https://user-images.githubusercontent.com/21282980/37625350-d90eeab0-2bcb-11e8-8470-b5d95691d56e.jpg)

i notice that the video with VBAQ appears stuttery - while the one without is more smooth
also VBAQ has an noticeable impact on the game - sometimes even lags

**Comment by Xaymar** [comment] 2018-03-19 22:26
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you. (Missing: Log Files with debugging active for all recordings uploaded)

**Comment by Benman2785** [comment] 2018-03-20 08:05
sry - will post new videos with correct logs in 30min(ish)

**Comment by Benman2785** [comment] 2018-03-20 09:27
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-20_10-12-50_VBAQ.txt
http://benmanshafen.de/obs/xaymar/2.3.3/noHRD_CABAC_VBAQ_tra_b2_que3-1521537385.flv

http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-20_10-08-41_without.txt
http://benmanshafen.de/obs/xaymar/2.3.3/noHRD_CABAC_tra_b2_que3-1521536941.flv

btw - i also try to reproduce a crash that sometimes occures with VBAQ enabled

**Comment by Xaymar** [comment] 2018-03-22 22:50
1. Configuration (for both)
    * Profile Level 3.1 may result in unexpected behavior, try 4.1 or higher.
    * Maximum QP controls the absolute maximum QP that the Rate Control Method can use, which negatively impact performance and size of the video.
    * Enforce HRD should be On for H264 content, but usually does not make a difference.
    * VBV Buffer Size is very small which may add to the maximum QP constraint issues.
2. Video itself (as shown in the log file)
    * Only _two_ frames where skipped and not encoded, which means no stuttering.

**Comment by Benman2785** [comment] 2018-03-23 09:33
can you please check the frametime?
because when i watch the video on my 144hz 1ms grey-to-grey screen i notice stutter

3.1 should be enough for 720p60 - but i change to 4.1
MaxQP will be tried - but i never run any issue on lowering it - because bitrate is always enough to stay around 33ish

**Comment by Xaymar** [comment] 2018-03-23 11:25
I did check the frame time, that's why i asked for a log file. Every single frame was encoded and returned to OBS, which saved that frame too:

- 10795 frames were drawn (10797 attempted).
- 10773 frames were written to disk/stream.
- 10774 frames were encoded by AMF.
- 10777 frames were submitted for encoding by AMF. (3 frame encode latency)
- Initial frame latency is 54.314 ms, or 2.607 frames.

That means that _all_ frames of the 3:44 long video were encoded _without stuttering_, as the encoded frame count matches the amount of frames stored by OBS perfectly. Any stuttering you see is likely due to the game itself or the capture method you chose to use.

**Comment by Benman2785** [comment] 2018-03-23 11:30
i mean the time between frames

like 1/48 = 0.02083 - but it looks some frames took 0.023s and others took 0.018s

do you have a 144hz 1ms screen? because if i watch it on my 75hz screen it looks fine - (most of the time)

**Comment by Benman2785** [comment] 2018-03-23 11:47
with MPC-HQ it is less noticecable

but in http://benmanshafen.de/obs/xaymar/2.3.3/720p48_h264+4872kbps_aac+128kbps_noHRD_CABAC_VBAQ_tra_b2_que3.flv (already downloaded) i still notice it - like at 0:16-0:18 or 0:19 when he pulls himself up - and that continues trhoughout the whole video

**Comment by Xaymar** [comment] 2018-03-23 11:52
The monitor does not matter for this as I am using frame by frame testing in a professional analyzer tool (VEGA H264). Additionally the frame times can't ever be different than the framerate, so every single frame it is exactly 20.8333ms.

Again, any stuttering you see is not by the encoder unless you actually have a number of frames skipped by encoding lag (which you don't).

**Comment by Benman2785** [comment] 2018-03-23 12:11
maybe its a problem by AMDs Video Decoder

yet VBAQ still impacts the game and didnt improve quality (for most scenarios) - but i think this is Mikhails job

**Comment by Xaymar** [comment] 2018-03-23 12:13
VBAQ does not help much, it is at most a 0.003%pt improvement that only helps with noisy textures and areas.

**Comment by Xaymar** [comment] 2018-06-18 20:39
Closing as this is not an issue with the plugin itself. For hardware and driver problems, please contact AMD support.

**Closed as completed by Xaymar** 2018-06-18 20:39 UTC
Labels: type:support
