### ISSUE TITLE
Plugin uses more bitrate than allowed.

### ISSUE THREAD

**Issue by wazerstar** [Xaymar/OBS-AMD-Advanced-Media-Framework#46] opened 2016-08-23 17:34 UTC
Plugin settings
http://prntscr.com/c9gi3u

Output
http://prnt.sc/c9ghk8
[Uploading 2016-08-23 19-36-17.txt…]()

**Comment by Xaymar** [comment] 2016-08-23 17:37
Both of those are empty screenshots for me, please follow [this guide for reporting issues](https://github.com/Xaymar/OBS-AMD-Media-Framework/wiki/Reporting-Issues).

**Comment by wazerstar** [comment] 2016-08-23 17:48
Pictures working fine, and log is there. ok I post it again.

Hardware:
CPU: Intel 4790K
Graphics: AMD R9 290 4GB GDDR5 modded to 290x - Then remodded to 390x
Motherboard: Asus MAXIMUS VI FORMULA
Ram: 16GB DDR3 2400mhz
Disk: 1TB Samsung EVO 840

[AMF Encoder] Version 1.3.0pre3-1.3.0.5

Offline pictures

![09ae904781264e30aa83b2d769a9ebfe](https://cloud.githubusercontent.com/assets/4474519/17903236/ffb7a082-696a-11e6-849c-0bd354fe0fe9.png)

![bc647f6907574d7cac6eb9dd60475af4](https://cloud.githubusercontent.com/assets/4474519/17903047/45569004-696a-11e6-8023-7019035de784.png)

**Comment by Xaymar** [comment] 2016-08-23 18:35
Please use the Simple Interface instead, the advanced interface is not complete yet. Using the Simple Encoder I had no issues meeting the bitrate I gave it, it often went lower than expected.

Also, VLC will not show the true footage bitrate. VLC uses a buffered loader, so it will always show more than it actually has. Use mediainfo or ffmpeg instead.

**Comment by Xaymar** [comment] 2016-08-26 09:35
Can't reproduce this expect when the encoder falls seriously behind - but even then it's only 15-25% off the target bitrate. Closing for now.

**Closed as completed by Xaymar** 2016-08-26 09:35 UTC
Labels: type:bug, status:solved
