### ISSUE TITLE
Starting the output failed - AMD Fall update

### ISSUE THREAD

**Issue by tazviney** [Xaymar/OBS-AMD-Advanced-Media-Framework#281] opened 2017-10-18 11:30 UTC
Motherboard: ASROCK 870 Extreme3 r2
CPU: AMD FX 8320
GPU: AMD RX 480
RAM: Corsair Vengence LP 8GB 1600
SSD: ADATA SP 600 120GB
HDD: Seagate Desktop HDD ST2000DM001 2TB
OBS Studio Version: 20.1.0
Installed Plugin Version 2.2.3
Installed AMD Driver Version: Non-WHQL-Win10-64Bit-Radeon-Software-Crimson-Beta-Fall-Update-Oct16
Log Attached: [2017-10-18 12-31-19.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1394405/2017-10-18.12-31-19.txt)
Issue:
For the fall drivers from AMD and builds from Microsoft The plugin is no longer working and comes up with "Starting the output failed". I can use Relive in AMD software. Rollback a driver and the plugin works fine.

**Comment by Xaymar** [comment] 2017-10-18 11:33
Caused by querying "CommonLowLatencyInternal", which has been removed according to that log file.

**Comment by b1n4ryk1lla** [comment] 2017-10-18 12:35
i have this issue too Drivers are latest

<Plugin::AMD::EncoderH264::GetCommonLowLatencyInternal> Failed to retrieve value, error AMF_INVALID_ARG (code 4)
08:26:45.355: Stream output type 'rtmp_output' failed to start!

**Comment by b1n4ryk1lla** [comment] 2017-10-18 13:03
also why is 2.2.2 no longer anywhere to download... sigh

**Comment by Xaymar** [comment] 2017-10-18 14:37
> also why is 2.2.2 no longer anywhere to download... sigh

What will 2.2.2 get you except for broken Constant QP? Also it's on the releases page.

**Comment by Xaymar** [comment] 2017-10-22 23:03
Fixed by 2.2.4 unless AMD did any other silent changes that didn't require an SDK update.

**Comment by Xaymar** [comment] 2017-10-22 23:16
2.2.4 is released to the public, get it here: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/tag/2.2.4

**Closed as completed by Xaymar** 2017-10-22 23:16 UTC
Labels: type:bug, status:solved
