### ISSUE TITLE
PC Crashes when trying recording "The Division" with 2.1.6 or 2.2.0 and 17.7.2

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#263] opened 2017-07-30 13:08 UTC
Windows 10 Creators x64
AMD FX-9590 @4.88
RX 480 8G (Nitro+ OC) - also when only Factory-OC
GigaByte 990FX-Gaming (will check VRMs this time too)
16G DDR3 @1736MHz CL10 (cant get it wroking with 4x4G@1866CL9)

OBS 19.0.3
Plugin ver - 2.2.0 (patreon-release)
Drivers 17.7.2 (ReLive is installed)

PC - crashes shortly in random times after starting recording // sometimes only falls back to windows - but then Radeon-Settings is crashed and cant be opened

LOG;
[2017-07-30 14-44-51.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1185691/2017-07-30.14-44-51.txt)

**Comment by Benman2785** [comment] 2017-07-30 13:11
now testing with twitch-preset + PrePass enabled
have added "--verbose --log_unfiltered"

LOG soon

**Comment by max20091** [comment] 2017-07-30 13:22
"View Mode 'Master' is active, avoid giving anything but basic support. Error is most likely caused by user settings themselves."

But anyway, I have few things you need to look at:

```
14:44:54.406: warning: deprecated pixel format used, make sure you did set range correctly
```

Is seems like Facerig cause this issue.

```
14:45:40.335: [game-capture: 'Game Capture'] attempting to hook fullscreen process: TheDivision.exe
14:45:40.341: [game-capture: 'Game Capture'] using helper (compatibility hook)
```
Can you disable compatibility hook?

```
14:45:43.356: [game-capture: 'Game Capture'] attempting to hook fullscreen process: TheDivision.exe
14:45:43.416: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
14:45:43.416: [game-capture: 'Game Capture'] Buffer count: 3, swap effect: 4
14:45:43.497: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
```

It seems like the game is running DX12, can you try to record with DX11?

```
14:46:45.176: [AMF] [H264]<Id: 6>     OpenCL: Supported
14:46:45.177: [AMF] [H264]<Id: 6>       Transfer: Enabled
14:46:45.177: [AMF] [H264]<Id: 6>       Conversion: Enabled
```
I dunno if these things cause performance issue but just disable it anyway


If all of them not work, revert to default and test again so you don't touch any unnecessary parameters

**Comment by Benman2785** [comment] 2017-07-30 13:34
1. i know that i use "Master" - and usually it works ;) - but with 17.7.2 AMD has changed something so the plugin is now crashing

2. with testing on "Twitch-Preset" it hasnt crashed in ~14min of recording - so some of the "View Mode Master" Options are broken now

3. thank you for your help so far ;)

4. nope - i HAVE to run it on DX12 - because its much smoother then - btw "The Division" is all my CPU can handle xD - when using "x264 Software" i have to force game on 6 Cores and OBS + Rest of System on 2 Cores ;)

5. OpenCL Transfer and Conversion have some impact on frametimes and reduce CPU-load - so thats actually something i should use

6. i will disable compatibility hook - but had problems with hooking some games since 17.5.1 - especially after Windows Creator Update (but that was OBS bug)

**Comment by Benman2785** [comment] 2017-07-30 13:41
here log form working "Twitch-Preset"

32mb - sry my server is slow (have to change hoster soon)
http://benmanshafen.de/OBS/VCE/v2.2.0/2017-07-30_15-09-54.txt
https://gist.github.com/8efb0adcd1ea96b9d317ad5aab0f4f30

**Comment by Benman2785** [comment] 2017-07-30 13:46
mh - after i have watched the footage i noticed that the frametimes are "to high" - so its with a little stutter

that wasnt the case with "Master View Mode" - i think OpenCL "Transfer" would help here

**Comment by Xaymar** [comment] 2017-07-30 13:59
By crash, do you mean a GPU driver reset? Also looking at your log there are some things that you can fix.

```
14:46:35.645: [AMF] [H264]<Id: 5>     OpenCL: Supported
14:46:35.645: [AMF] [H264]<Id: 5>       Transfer: Enabled
14:46:35.645: [AMF] [H264]<Id: 5>       Conversion: Enabled
```

Please disable OpenCL and try again. OpenCL is not faster than using DirectX/DirectCompute directly and may cause issues if the system has other drivers installed that also provide OpenCL capabilities. The only effect OpenCL has is slightly more stable times for frame submission and packet retrieval, which usually end up being much higher than what you want for live recording.

```
14:46:35.646: [AMF] View Mode 'Master' is active, avoid giving anything but basic support. Error is most likely caused by user settings themselves.
```

Please reproduce the issue without using View Mode Master.

> mh - after i have watched the footage i noticed that the frametimes are "to high" - so its with a little stutter

The stutter is normal when running OBS with --verbose --unfiltered_log while Debug is checked. The plugin then spews out several hundred lines of log data per second, which OBS wasn't made to handle well - it does better on faster CPUs (Ryzen, current Intel) but an FX will run into issues quickly.

**Comment by Benman2785** [comment] 2017-07-30 14:24
i think i know now why the crash happens - i set my CPU to 33% Power-Target -> now with 25% i havent had issues // 25% = max 187W - and my GPU pushes to 180W

i think Gaming + VCE + PrePass let the GPU draw to much power as peak with target risen

btw - i noticed better frametimes with OpenCL activated with my FX-CPU // will now disable logging options and test both on "Advanced View Mode"

**Comment by Xaymar** [comment] 2017-07-30 14:26
OpenCL has no effect on encoding and should have no effect on game fps. If it does have an effect on game FPS you should consider getting a faster CPU.

**Comment by Benman2785** [comment] 2017-07-30 14:40
i dont mean ingame-FPS - i mean frametimes of resulting video
i post 3 files here and upload to YT - will take 5min 

btw i will get a faster CPU xD // but FX-9590 @4.88GHz should be able to use your Plugin :p

**Comment by Benman2785** [comment] 2017-07-30 14:42
LOG: https://gist.github.com/1cc4e325ef00fdcb688893038fac9e7b or http://benmanshafen.de/OBS/VCE/v2.2.0/2017-07-30_16-20-02.txt

without OpenCL
MF: https://www.mediafire.com/?6ypzrrwl12arwmv
org: http://benmanshafen.de/OBS/VCE/v2.2.0/v2.2.0-twitch-Custom_Buffer-no_OpenCL.mkv
YT: https://youtu.be/61hkapRkPcY

with OpenCL Transfer
MF: https://www.mediafire.com/?5zmf4f47fhqe84d
org: http://benmanshafen.de/OBS/VCE/v2.2.0/v2.2.0-twitch-Custom_Buffer-OpenCL_Transfer.mkv
YT: https://youtu.be/yz9-_6mepf0

with both OpenCL
MF: https://www.mediafire.com/?roke6kuaa2j840m
org: http://benmanshafen.de/OBS/VCE/v2.2.0/v2.2.0-twitch-Custom_Buffer-OpenCL_both.mkv
YT: https://youtu.be/6RKB8DDr6g8

**Comment by Xaymar** [comment] 2017-07-30 14:46
> i dont mean ingame-FPS - i mean frametimes of resulting video

Frame time of resulting video is untouched by either. There is a large frame and packet queue that nullifies almost all hitches/stuttering. If you see a difference, provide original (non-YouTube or Twitch) and their log file counterparts.

**Comment by Xaymar** [comment] 2017-08-03 19:38
Provided log file was not created using Debug, --verbose --unfiltered_log must be added to the obs-studio shortcut for full debug information to be visible. See the Troubleshooting Guide for details.

**Comment by Benman2785** [comment] 2017-08-04 10:16
LOG: 
here tested DX9 - same error as DX11
[2017-08-04 12-07-46.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1199985/2017-08-04.12-07-46.txt)

OBS CRASH:
[Crash 2017-08-04 12-12-33.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1199987/Crash.2017-08-04.12-12-33.txt)

**Comment by Benman2785** [comment] 2017-08-05 09:04
[2017-08-05 10-35-28.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1202248/2017-08-05.10-35-28.txt)

after further testing: the problem is PrePass - with it disabled all is fine (shon in this log) && when i enable it OBS (and sometimes also the Game) crashes - with the error provided in log "2017-08-04 12-07-46.txt" and OBS Crash // that crash occures after starting recording in max 15min

**Comment by Benman2785** [comment] 2017-08-05 16:52
LOG: [2017-08-05 18-22-30.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1202524/2017-08-05.18-22-30.txt)
Dump: https://www.mediafire.com/file/f81jcrlftp3yl7m/obs64_dump.7z

**Comment by Benman2785** [comment] 2017-08-09 21:11
still persists in 2.2.2 - yet it could record 3min longer then before xD

**Comment by Xaymar** [comment] 2017-08-10 09:49
Please repeat the tests with the --unfiltered_log --verbose options applied to OBS, while Debug is also checked in the encoder options.

**Comment by Benman2785** [comment] 2017-08-10 13:07
[2017-08-10 14-48-23.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1214975/2017-08-10.14-48-23.txt)

first encoding error starts at: 15:02:34.542

**Comment by Benman2785** [comment] 2017-08-10 13:16
15:02:34.542: [AMF Runtime] [15:02:34.542][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=23450, outputFrames=23441
15:02:34.542: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:02:34.543: [AMF Runtime] [15:02:34.543][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=23450, outputFrames=23441
15:02:34.543: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code `24).


15:02:34.571: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:02:34.573: [AMF] <Id: 7> No output Packet, encoder is overloaded!
15:02:34.574: [AMF] <Id: 7> EncodeStore: PTS(   23450) DTS(   23450) TS(      4885416667) Duration(          208334) Type(Automatic)
15:02:34.574: [AMF Runtime] [15:02:34.574][AMFEncoderVCE]    Trace: SubmitInput() End: frame pts=4885416667 inputFrames=23451, TaskID=23453
15:02:34.575: [AMF] <Id: 7> [Main/Submit] SubmitInput returned AMF_OK (code 0).
15:02:34.575: [AMF Runtime] [15:02:34.575][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=23451, outputFrames=23441
15:02:34.575: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).


15:02:34.794: [AMF] <Id: 7> No output Packet, encoder is overloaded!
15:02:34.797: [AMF] <Id: 7> EncodeStore: PTS(   23456) DTS(   23456) TS(      4886666667) Duration(          208334) Type(Automatic)
15:02:34.797: [AMF] <Id: 7> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:02:34.797: [AMF Runtime] [15:02:34.797][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=23456, outputFrames=23441
15:02:34.797: [AMF] <Id: 7> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:02:34.799: [AMF] <Id: 7> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:02:34.799: [AMF Runtime] [15:02:34.799][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=23456, outputFrames=23441

**Comment by Xaymar** [comment] 2017-08-10 14:14
I have attempted to reproduce this for over 3 hours and not gotten any GPU driver crash. Make sure that your GPU drivers have been installed cleanly (see FAQ) and that your GPU is not overclocked, modded or using any other non-AMD extensions.

**Comment by Benman2785** [comment] 2017-08-10 14:24
i do

i will reinstall 17.7.2 with DDU in SafeMode - run without OC and using no other stuff

**Comment by Benman2785** [comment] 2017-08-10 15:13
crashed after 14:58min - so maybe i need to test more then 15min on other games now too

**Comment by Benman2785** [comment] 2017-08-12 15:37
looks like it has to do with GPU using HWacc on second screen ;)

**Comment by Xaymar** [comment] 2017-08-12 16:57
So it is confirmed to not be an issue with the plugin or AMF? If so, then I will close this issue.

**Comment by Benman2785** [comment] 2017-08-12 17:32
yes u can xD

**Closed as completed** 2017-08-12 17:56 UTC
Labels: type:support

**Comment by Benman2785** [comment] 2017-10-25 00:03
still crashes with new RX580 - but 17.6.2 DOESNT CRASH! - so it IS a software error - pls re-open

[2017-10-25 01-52-18.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1412846/2017-10-25.01-52-18.txt) now with error code ;) - will add required log tomorrow

[Crash 2017-09-08 16-02-31.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1412847/Crash.2017-09-08.16-02-31.txt) - from older crash that day

**Comment by Benman2785** [comment] 2017-10-25 01:26
i also can say its NOT your Plugin or AMF 1.4.6.0 // so it can be the new pixel-engine used since 17.7.1-2 or the "reduced-input-lag"-fixes with that drivers

**Comment by Benman2785** [comment] 2017-10-25 01:32
Speed-Test of my 17.6.2 with AMF 1.4.6.0 (from 17.10.2 - notice h265 not working)
[RX580.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1412971/RX580.zip)
