### ISSUE TITLE
Pre5 Issue

### ISSUE THREAD

**Issue by locodicegr** [Xaymar/OBS-AMD-Advanced-Media-Framework#58] opened 2016-08-27 07:31 UTC
My previous issue is gone from here?
I had the overload problem and the ''stop recording got stuck"
now i got passed this problem - stop recording was execute correct without stuck, opened the recording file
main menu recorded ok...but when it got into the game it got freeze into a scene,

[2016-08-27 10-08-59.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440533/2016-08-27.10-08-59.txt)
[2016-08-27 10-16-36.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440534/2016-08-27.10-16-36.txt)
[2016-08-27 10-27-11.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440535/2016-08-27.10-27-11.txt)

**Comment by locodicegr** [comment] 2016-08-27 07:37
https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/issues/43

My previous issue, that didnt find. got renamed. lol.

**Comment by Xaymar** [comment] 2016-08-27 08:42
Same issue as before. 
1. You are using 32-bit on a 64-bit capable system, this can heavily impact performance. Also the 32-Bit amfrt version is mostly untested on my end due to 64-bit being the future. Embrace the future and use it.
2. Enable Debug Tracing before trying again.

**Comment by locodicegr** [comment] 2016-08-27 10:44
Well, how im using the 64 bit? you mean 64 bit obs studio?
Or....??

**Comment by Xaymar** [comment] 2016-08-27 10:44
Yes, 64-Bit OBS Studio.

**Comment by locodicegr** [comment] 2016-08-27 11:03
well, i cant find such thing to download.
there is only 1 link that doesnt say 32 neither 64.

**Comment by Xaymar** [comment] 2016-08-27 11:16
It installs both versions depending on what system architecture you have. If you have a 64-bit windows, just open the "OBS Studio (64-Bit)" shortcut instead.

**Comment by max20091** [comment] 2016-08-27 12:19
uninstall and reinstall plugin again will help you partially.
64 bit version is in [obs-studio-location]\bin\64bit

**Comment by nwgat** [comment] 2016-08-27 13:05
Windows  Key + R then `C:\Program Files (x86)\obs-studio\bin\64bit\obs64.exe` and Enter

**Comment by locodicegr** [comment] 2016-08-27 18:23
Yeap tried it but now i got black recording screen.

Its messing with me head..soon i will format the windows anyway.

I will try from scratch.

Thanks everyone.

**Comment by Xaymar** [comment] 2016-08-27 21:56
Duplicate of #43

**Closed as completed by Xaymar** 2016-08-27 21:56 UTC
Labels: type:duplicate, status:solved
