### ISSUE TITLE
Artifacting in the first few minutes of streaming/recordung

### ISSUE THREAD

**Issue by k0zyrev** [Xaymar/OBS-AMD-Advanced-Media-Framework#151] opened 2016-11-20 09:03 UTC
steps 1-5 done, went to obs forums for help, got redirected here to submit an issue

1. dxdiag http://pastebin.com/raw/K4eiijss
2. 0.16.5
3. 1.4.2.3
4. 16.11.4 / 16.40.3211-161115a-308833E
5. video: https://drive.google.com/open?id=0B-MVqNVDSsJ5WEJHZTlZdzg2ekU
log: https://gist.github.com/anonymous/146aac62f5d550dbe722c25f3742a702
6. Getting major artifacting in first few minutes of streaming/reconding, then it goes away
screenshots
http://i.imgur.com/qFy8zFh.jpg - http://i.imgur.com/ZNObVcG.jpg
http://i.imgur.com/BNeQu5A.jpg - http://i.imgur.com/oD24zOf.jpg
http://i.imgur.com/E7N5sY8.jpg - http://i.imgur.com/vHhR8Ia.jpg

**Comment by Xaymar** [comment] 2016-11-20 17:34
Your linked pastebin is private, I can't view it.

**Comment by k0zyrev** [comment] 2016-11-20 17:49
my bad, it should be available now

**Comment by Xaymar** [comment] 2016-11-20 18:31
I can see what you mean in the recorded file, I'm unsure why it happened though. I'll try to reproduce on my hardware if at all possible.

**Comment by everyth1ng** [comment] 2016-11-20 22:28
I see that this is open. Let me know if you'd still like me to make another Issue.
1. [DxDiag.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/602382/DxDiag.txt)
2. 0.16.5
3. 1.4.2.3
4. 16.11.3
5. Video: https://www.twitch.tv/everyth1ngtv/v/101951983 
   Log: [2016-11-18 22-44-10.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/602384/2016-11-18.22-44-10.txt)

**Comment by Xaymar** [comment] 2016-11-20 22:54
Looks like you have the same issue, wonder if it's exclusive to a specific VCE version. What cards do you both have? (Full vendor name, like ASUS Radeon R9 285 Strix II OC DirectCU)

**Comment by everyth1ng** [comment] 2016-11-20 23:00
XFX Radeon R9 290

**Comment by k0zyrev** [comment] 2016-11-21 03:56
Sapphire Radeon Dual-X R9 270X

**Comment by Xaymar** [comment] 2016-11-21 17:00
Hmm, VCE1.0 and VCE2.0. Have both of you tried encoding with the GPU at reference clock speeds?

* R9 290 Reference clock speeds: 947 Mhz GPU, 1250 Mhz Memory
* R9 270X Reference clock speeds: 1000 Mhz GPU, 1400 Mhz Memory

Technically I should be able to reproduce this on either of my cards, but so far had no luck doing so.

**Comment by everyth1ng** [comment] 2016-11-21 18:29
Yeah, same results at 947 Mhz/1250 Mhz: https://www.twitch.tv/everyth1ngtv/v/102511106

**Comment by Benman2785** [comment] 2016-11-21 18:41
should i test with RX 480? - so i would need the settings

**Comment by Xaymar** [comment] 2016-11-21 21:07
I've tested several hours with both my R9 285 and RX 480 now, there are no artifacts at the beginning of any recordings. I will test streaming and see if I can make it happen there - if so, the issue is actually in OBS itself.

**Comment by everyth1ng** [comment] 2016-11-21 21:24
@Benman2785 Check my log above to see my settings. I'm essentially using the Twitch preset, though.

**Comment by Xaymar** [comment] 2016-11-21 23:34
I've reported this to AMD now: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/46

Unfortunately I have still been unable to reproduce this at all. I have been able to find out what happened with ffprobe though, seems that some packets of the h264 bytestream are corrupted for an unknown reason, causing any blocks contained in that packet to also be corrupted.

Edit: Mikhail informed me that it is a different manifestation of the bug reported here: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/41

**Comment by everyth1ng** [comment] 2016-11-22 06:04
At least they're aware of it. No ETA on when the fix will be released?

**Comment by Xaymar** [comment] 2016-11-22 06:16
It will most likely not be in a hotfix driver.

**Comment by everyth1ng** [comment] 2016-11-22 06:23
IIRC, they have a large update coming soon, anyway. Looking forward to it!

**Comment by Xaymar** [comment] 2016-11-27 15:36
Same bug as in #143, however a different manifestation of what causes it. Instead of crashing it causes data corruption.

Merging to #143.

**Closed as completed by Xaymar** 2016-11-27 15:36 UTC
Labels: type:duplicate
