### ISSUE TITLE
Wrong Bitrate in Metadata with FLV format.

### ISSUE THREAD

**Issue by Zerowalker** [Xaymar/OBS-AMD-Advanced-Media-Framework#92] opened 2016-09-25 00:09 UTC
Mentioned this on Hexchat.

Nothing serious, but just putting it here if someones decides to fix it at some point.

I said i use FLV cause of crash resistance, but i forgot that it also has better seekability compared to MKV with OBS.

Cause for some reason MKV with OBS is unseekable, making it Super Slow as it has to read up to the seek point Every time a seek occurs.

FLV on the other hand keeps a buffer so if you read to the end of the file one time, it will seek fast until the media player closes.
(Still kinda sucks, but compared to the MKV thing it's much better, just imagine how slow it is to seek a 30gb 2 hour file -_-).

**Comment by Xaymar** [comment] 2016-09-25 00:16
I don't think I can fix this, it's something OBS's muxer thing has to fix.

**Comment by Zerowalker** [comment] 2016-09-25 01:20
The FLV thing?
The MKV thing i can understand, though that one is a mystery why it happens,
even Jim don't get it as it's ffmpeg that does the muxing.

As for the bitrate in FLV, it looks fine with VCE MF,
so shouldn't that mean that the muxing part is fine, but the encoded metadata is not?

**Comment by Xaymar** [comment] 2016-09-25 01:25
I don't handle metadata, I only have control over the timestamp of individual packets. Like I said, it's a muxing issue.

**Comment by jp9000** [comment] 2016-09-25 01:45
There isn't any known problem with muxing in obs.  I basically just pass everything to the FFmpeg muxer.  I'm not saying that's not the issue, I'm just stating that I haven't had any similar reports.

The only thing it might expect from your encoder is the "bitrate" setting, but I'm pretty sure FFmpeg mostly just treats it as metadata, not something that affects file playback at all.

Unfortunately I can't help test this issue because I don't have an AMD video card to test with at the moment.  I'll have to build a new computer to be able to do that.  I do doubt that the FFmpeg muxer is at fault however.

**Comment by Zerowalker** [comment] 2016-09-25 01:56
Well, something is at fault for whatever reason.

It's probably as Jim says, that it takes the bitrate setting, though if i understand it right,
it seems that the bitrate is for some reason wrong in time.

So, longer videos = MUCH higher bitrate.
In that case, one would guess that the metadata for some reason says "video is, say 1 sec",
and then looks a the size which is off the scale for that length.

ffmpeg can probably not be at fault as AMD VCE MF works.
But then again, i have no idea how it handle things, perhaps it has more access than your Plugin based version?

It does not seem to affect playback as stated, so fixing this issue is just to correct a simple "bug" if you will:)

Jim, not sure if the first sentences are about the MKV unseekable issue or if you are talking about the FLV.

If the MKV issue, then it's only in MKV, the solution is to use MP4, but sadly it's not crash resistant.
I have no idea why MKV is unseekable for me (always has been), i don't know if others have actually tried using it that way (seeking on huge files).

I believe it's common to use FLV and MP4 on OBS.

Yay wall of text:)

**Comment by jp9000** [comment] 2016-09-25 02:47
There's no need to assume.  The cause will eventually be found through testing, so long as testing is done.

**Comment by Zerowalker** [comment] 2016-09-25 03:24
The assumptions are done from my part of testing, not just from thin air.
Though that being said, it's not worth much as a sole tester.

I will gladly test anything that will help in anyway for the progress of the plugin or OBS:)

**Comment by Xaymar** [comment] 2016-09-25 08:51
Bitrate Thing: I think I fixed it, but I'm not sure. It never really happened for me as MediaInfo always displayed the average bitrate. 

Seeking Issue: That I can't fix. As before I already had issues with [timestamps](https://obsproject.com/mantis/view.php?id=614) that would cause packet duplication and reordering, I'm not sure if ffmpeg is not at fault here. VLC can seek without issues in it, so perhaps it's something to do with decoders not being standard compliant.

**Comment by Xaymar** [comment] 2016-09-25 18:16
Fixed in 1.3.0rc5, I hope.

**Comment by Xaymar** [comment] 2016-09-27 01:24
Seems to be fixed, at least for me. If it reappears, please open this issue again.

**Closed as completed by Xaymar** 2016-09-27 01:24 UTC
Labels: type:bug, status:solved

**Comment by Zerowalker** [comment] 2016-09-27 23:55
Metadata seems fixed, but the video is corrupted when decoded with LAV Filter for some reason.
VLC works fine, weird:s

**Comment by Xaymar** [comment] 2016-09-28 19:45
The decoder needs to be standard compliant to both the muxed format and H.264, if it isn't then it'll run into issues pretty early. Nothing I can fix.

**Comment by Zerowalker** [comment] 2016-09-29 00:53
So LAV Filter isn't?
I am surprised, will probably have to test things out later, thanks:)

**Comment by Xaymar** [comment] 2016-09-29 00:55
If it isn't playing it back properly, then no it isn't. The files work fine with MPC-HC, VLC and ffmpeg.

**Comment by Zerowalker** [comment] 2016-09-29 01:14
i am using MPC-HC, this was with B-Frames to 3 and B Reference if i recall.
Probably something on my side, will report back when i do some more testing:)

**Comment by Zerowalker** [comment] 2016-10-04 01:20
It seems to have been related to Deblocking filter being disabled for some reason.

Though i have a bigger problem now, i noticed that i can't record for longer periods.
The video stops recording/encoding, but the audio is fine.

I don't know if it's random, size or length that causes it. It seems to be around 20-30 min.
And that's with 60fps, 30000 bitrate 50000 peak, no B frames, CABAC enabled. 1920x1200.
(tried a bit of different settings, but bitrate, fps and resolution has been the same)

EDIT:

It might be duration based, it seems to occur at about 20:50, for whatever reason.
Even if size differs.

**Comment by Xaymar** [comment] 2016-10-04 06:59
Update your plugin to 1.3.2.1. It was fixed last version.

**Comment by Zerowalker** [comment] 2016-10-04 07:06
Oh, nice, will try it out:)

Btw, is OpenCL supposed to be slower (Compute Method?)
Cause it's really slow for me, which i guess defeat the purpose, normally it's faster as it's offloading.

**Comment by Xaymar** [comment] 2016-10-04 07:08
OpenCL technically should be faster, but there is a bug in the driver which makes it slower. The best speedup the plugin can get anyway is if OBS directly shared DirectX11 and OpenGL surfaces instead of copying these to RAM.

**Comment by Zerowalker** [comment] 2016-10-04 07:13
Ah, remember you talking about that before, something the Old OBS VCE does right?
And the reason you haven't done is, was, what?
Too complicated etc, or that the plugin system doesn't really allow it?

It's looking awesome either way, you get my praise, take it!;d

**Comment by Xaymar** [comment] 2016-10-04 07:14
Yeah, the old OBS does that. The reason I haven't done it is because it's not an exposed feature from OBS.

**Comment by Zerowalker** [comment] 2016-10-04 07:21
Ah, which technically means the plugin system doesn't support it?

Still, how much do you expect to gain from that, it should be quite a lot in terms of bandwidth,
though i not sure how often it's bottlenecked, but perhaps during high GPU Load.

**Comment by Xaymar** [comment] 2016-10-04 07:29
Right now the main bottleneck is bandwidth. At 1920x1080 60Fps NV12 it takes 88 megabyte per second of GPU bandwidth just for the frames themselves.

**Comment by Zerowalker** [comment] 2016-10-04 07:38
Oh, doesn't sound That much though?
But then again, i don't know how much Bandwidth there is to spare.

Have Jim said anything about this feature, as i guess cooperation is needed if it's to be implemented?

**Comment by Xaymar** [comment] 2016-10-04 14:04
I have added a feature request to mantis, but so far no word about it: https://obsproject.com/mantis/view.php?id=610

**Comment by Zerowalker** [comment] 2016-10-04 14:14
Ah i see, well then he probably knows about it at least:)

Oh, btw, it seems that randomly some encodings still get messed up bitrate.

Latest version (1.3.2).

Bit rate                                 : 18446743 552 Gbps
Bits/(Pixel*Frame)                       : -0.000
Stream size                              : 2.05 ?iB

Most of the time it seems to work i think.

**Comment by Xaymar** [comment] 2016-10-04 14:19
No idea why that happens, I have everything set properly on my end now. It generally isn't recommended to rely on metadata for actual data anyway, so this isn't a big deal.

**Comment by Zerowalker** [comment] 2016-10-04 14:27
Well it's weird, cause it's random, only thing i can guess is that the data is sometimes not used for some reason.

And yeah know it's just info data, just wanted to pass it on:)
