### ISSUE TITLE
Encoding perma-dies after about ~20 start-stops

### ISSUE THREAD

**Issue by Vectrobe** [Xaymar/OBS-AMD-Advanced-Media-Framework#375] opened 2019-06-08 08:00 UTC
https://obsproject.com/logs/BRg1GMLUF3VLRoD7

May or may not be a VII-exclusive issue, I no-longer have a V64 to test with (returned due to the SoC bug), and my 290X isnt exactly great to test with either.

![image](https://user-images.githubusercontent.com/3912867/59144182-28820000-8a17-11e9-9e2b-6b23f30ae74e.png)

All subsequent videos end up dead-green, OBS has to be restarted to work properly again, of which it works perfectly when it does.

**Comment by Xaymar** [comment] 2019-06-09 14:46
I haven't seen this before, but it might have to do with this:

`17:47:59.537: [AMF] [H264]<Id: 28>     Format: RGBA 601 Partial`

I strongly recommend only ever using NV12 with AMD encoding, as all other color formats require converting before encoding.

**Comment by Xaymar** [comment] 2019-06-10 14:00
```
17:47:49.392: [AMF] [H264]<Id: 22>     OpenCL: Supported
17:47:49.392: [AMF] [H264]<Id: 22>       Transfer: Enabled
17:47:49.392: [AMF] [H264]<Id: 22>       Conversion: Enabled
```

OpenCL is not recommended, due to the higher latency, higher impact on GPU usage and lower performance and support compared to standard DirectX.

**Comment by Vectrobe** [comment] 2019-06-12 05:07
alright, will test with those changes. I had OCL t&c enabled as it fixed a stutter issue I had on prior cards, don't remember however if it still affected the VII I now own. Format wise I probably had it set to RGB due to a colour issue, but we'll see what happens.

**Comment by Xaymar** [comment] 2019-07-06 20:52
This problem might be reduced once #378 is implemented.

**Comment by Xaymar** [comment] 2019-07-20 21:12
Have you been able to reproduce the issue with the fixed settings at all? I am unable to repro this bug with an RX 480 or a VII

**Comment by Vectrobe** [comment] 2019-07-23 06:36
yea, nah I haven't had it happen again. There's still however some cases of stutter, with OBS outright failing to capture displays and windows on occasion, though I'm pretty sure these are unrelated to the actual encoding side...

**Comment by Xaymar** [comment] 2019-09-29 10:35
Closing as potential Driver+Hardware issue.

**Closed as completed by Xaymar** 2019-09-29 10:35 UTC
Labels: type:support
