### ISSUE TITLE
OpenCL runtime from Intel Graphics Drivers are causing crashes

### ISSUE THREAD

**Issue by seccentral** [Xaymar/OBS-AMD-Advanced-Media-Framework#317] opened 2018-04-12 15:41 UTC
Heya, I just can't use dedicated AMD encoding at all. whenver I start the recording OBs tells me "obs has crashed" 
This is the log. 
Env: Win 10 64bit
amd 18.3.4 drivers
Video card RX 480 gaming X 8gb
[obs-amd-crashlog.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1903906/obs-amd-crashlog.txt)

**Comment by Xaymar** [comment] 2018-04-12 16:10
This looks like a crash that is currently being investigated by AMD. Please provide a normal log that matches the crash log. If you can reproduce the crash, please also attach a log of an obs instance started with the command line "--unfiltered_log --log_unfiltered --verbose" (no quotes).

**Comment by Xaymar** [comment] 2018-04-12 16:20
Oh and if you could upload a DMP file of the crashed process, that may actually help speed fixing this bug. Creating a DMP file of a process is fairly easy:

1. Get OBS Studio to the point where it crashes and once the crash handler opens, do not click anything in it.
2. Instead open the Task Manager ([Ctrl] + [Shift] + [Escape]) and go to the "Details" tab.
3. Then find obs##.exe, where ## is 32 or 64 depending on what you use, and right click on it.
4. Now click "Create Dump File" and wait for that process to complete.
5. Once that is complete, it will show you a path to a .DMP file.

This is the file that AMD needs, it will always be in the Temp directory. The file is uncompressed memory, so it is best if you compress it using WinRar or 7-Zip to .rar or .7z. Do not upload it publicly visible, instead send the link or file to info@xaymar.com with the subject being this issue.

Thanks in advanced.

**Comment by seccentral** [comment] 2018-04-12 16:34
Thanks. done sending the mail to info@xaymar.com

**Comment by Xaymar** [comment] 2018-04-12 17:56
Thank you, I've sent it along to AMD.

**Comment by Benman2785** [comment] 2018-04-21 13:04
just give it a try:

disable "high-dpi scaleing" and "Fullscreen optimizations" for the application you capture

**Comment by Xaymar** [comment] 2018-04-21 22:04
@Benman2785 This is not relevant to the issue (look at the crash log), the crash is caused by the Intel OpenCL runtime being loaded instead of the AMD Runtime. A fix is being worked on by AMD.

**Comment by Xbye** [comment] 2018-06-10 02:06
Wow... this is from April 21st. I am a bit appalled at how long this is taking to get fixed. I have been using old drivers for a long, long time and decided to update my drivers and am running into this exact same issue where trying to initialize the encoder causes OBS to immediately lock up. I will try uninstalling Intel with DDU... but that's going to limit my encoding options.

**Comment by Xaymar** [comment] 2018-06-10 10:05
The actual issue is at least a year old now. It really sucks that AMD takes this long to fix a very basic error... (if it is actually caused by them).

**Comment by Xaymar** [comment] 2018-06-18 20:53
Spoke with Mikhail about this, apparently this should have been fixed in Driver Version 18.3.4 (17.50.33.05), posted on March 26. If everyone that still experiences this problem try a full fresh reinstall (Display Driver Uninstaller in Safe Mode, reinstall latest Driver from amd.com) and confirm that would be great.

**Comment by Xaymar** [comment] 2018-06-18 21:09
If the driver does not work, the solution on the Frequently Asked Questions (which you should have read by now) will solve the problem: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-ffmpeg-shows-an-error-that-avcodec-avutil-and-avformat-are-missing-after-enabling-opencl-features .

**Comment by Xaymar** [comment] 2018-07-18 05:41
Closing as there has been no update for a month. Considering solved by either the new driver or the FAQ entry.

**Closed as completed by Xaymar** 2018-07-18 05:41 UTC
Labels: type:bug, status:wontfix
